### PR TITLE
9722 fix alignment of event items and its children

### PR DESCRIPTION
**Pull request by trimentor**
Issue: https://github.com/gitlabhq/gitlabhq/issues/9722

Could reproduce the issue on:
- GitLab Community Edition 8.1.2 <4e54222>
- gitlab-development-kit

How to reproduce:
1. Navigate to "/dashboard/activity" on a tablet in portrait mode or resize your desktop's browser window to a width of "768px".
2. Push code to a branch with a long name
3. A combination of a long first line (mentioning the name of your branch) and a timeago value of "about an hour ago" will push the first line downwards

### CODE REVIEW

**Comment by Razer6** [comment]
Could you provide screenshots?

**Comment by trimentor** [comment]
I used https://gitlab.com/gitlab-org/gitlab-ce/activity and created screenshots before and after I applied the patch.

**BEFORE**

*Firefox v42.0*

firefox-v42-before-tablet-portrait-mode

*Internet Explorer 11*

ie11-before-tablet-portrait-mode

**AFTER**

*Firefox v42.0*

firefox-v42-after-tablet-portrait-mode

*Internet Explorer 11*

ie11-after-tablet-portrait-mode

*Narrow viewport*

firefox-v42-after-change-mobile-portait-mode

**Comment by trimentor** [comment]
I used https://gitlab.com/gitlab-org/gitlab-ce/activity to serve as an example.and created screenshots before and after I applied the patch.

I've also reproduced this issue on:

* GitLab Community Edition 8.1.2 <4e54222>
* gitlab-development-kit (latest checkout)

**BEFORE**

*Firefox v42.0*

*Tablet portrait mode*

mozilla-firefox-v42-before

*Narrow viewport*

mozilla-firefox-v42-narrow-screen-before

**AFTER**

*Firefox v42.0*

*Tablet portrait mode*

mozilla-firefox-v42-after

*Narrow viewport*

mozilla-firefox-v42-narrow-screen-after

**Comment by randx** [comment]
@trimentor @Razer6 thank you

**Comment by trimentor** [comment]
You're welcome guys. Thank you for this amazing project

**Comment by randx** [comment]
@trimentor thank you for contributing :heart:

**Pull request merged**
