### PR TITLE
#9035 + #5936 Preserve trailing new lines at the end of file

### PR DESCRIPTION
**Pull request by kylekatarnls**
If the content end with a new line, add it as raw

### CODE REVIEW

**Comment by stanhu** [comment]
I don't think marking up the HAML is the right solution for this issue. df3c466e37fd was supposed to address this issue, but there may have been a regression introduced in a3d879d4.

**Comment by jvanbaarsen** [comment]
We can only accept a merge request if all the tests are green. I've just restarted the build. When the tests are still not passing after this restart and you're sure that is does not have anything to do with your code changes, please rebase with master to see if that solves the issue.

**Comment by jvanbaarsen** [comment]
This merge request has been closed because a request for more information has not been reacted to for more than 2 weeks. If you respond and conform to the merge request guidelines in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#pull-requests) we will reopen this merge request.

**Comment by braykov** [comment]
Preserving trailing new lines also means not adding such. Now I see that if a file does not end in a new line, the web editors adds a trailing line. And this is a change I have not made. Has anyone looked into this?

**Comment by kylekatarnls** [comment]
Yes, it was the purpose of this pull request but it has not been merged, it need to be rebased. This one should be a valid rebased pull request: #9884

**Comment by dblessing** [comment]
I agree with @stanhu original comment. This should be solved elsewhere. I'm not sure where/how, unfortunately.

**Comment by kylekatarnls** [comment]
I don't think so because it's a HAML "bug" IMHO so it must be solved in HAML.

**Pull request closed without merging**
