### PR TITLE
[wip] upgrade to RSpec 3

### PR DESCRIPTION
**Pull request by NARKOZ**
#7073 revised

### CODE REVIEW

**Comment by jvanbaarsen** [comment]
@NARKOZ Just checking in to see if you're still working on this?

**Comment by NARKOZ** [comment]
@jvanbaarsen how can I restart the build?

**Comment by jvanbaarsen** [comment]
@NARKOZ Hm, I think somehow its not possible with this PR, maybe close this PR and open a new one?

**Comment by NARKOZ** [comment]
Ok, I'll split it to several small PRs.

On Monday, February 2, 2015, Jeroen van Baarsen <notifications@github.com>
wrote:

> @NARKOZ <https://github.com/NARKOZ> Hm, I think somehow its not possible
> with this PR, maybe close this PR and open a new one?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gitlabhq/gitlabhq/pull/8463#issuecomment-72383669>.
>


-- 
--

Nihad Abbasov

**Comment by jvanbaarsen** [comment]
@NARKOZ Yeah think thats better :)

**Pull request closed without merging**
