### PR TITLE
Diff headers made sticky

### PR DESCRIPTION
**Pull request by yglukhov**
This is a reboot of #7611. I was really hoping to make use of semantic-ui/sticky or bootrstrap.affix, but unfortunately none of them worked for me. This new dependency `jquery.sticky-kit` seems to perform just great for our needs. Tested on latest Chrome, Safari and Firefox.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://yglukhov-diff-sticky-headers.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://yglukhov-diff-sticky-headers.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by randx** [comment]
Thanks

**Comment by yglukhov** [comment]
Thanx!

**Comment by randx** [comment]
@yglukhov I have an issue with this sticky headers when scrolling: 

screenshot_2015-05-27_16 37 50

Can you help me with that? Its really annoying :)

**Comment by yglukhov** [comment]
@randx, sure, I will look at it.

**Comment by randx** [comment]
@yglukhov sorry for pinging you but any news with this problem? I am afraid we would revert this feature otherwise.

**Comment by yglukhov** [comment]
@randx, sorry for silence. I could not reproduce the issue. Neither with https://gitlab.com/gitlab-org/gitlab-ci/merge_requests/109/diffs nor with my local setup. Tested with Safari 8.0.6 and Chrome 43.0.2357.124. Can you please provide some additional steps. Can you reproduce this with Safari or Firefox? Are there any Chrome extensions that may cause this problem?

**Comment by randx** [comment]
@yglukhov interesting. Now I can not reproduce it. Maybe it was magically fixed in last 2 weeks. Anyway thank you looking into it. If I experience this again - I will comment with exact steps to reproduce. Again thank you for looking into it.

**Comment by randx** [comment]
@yglukhov ok I was able to reproduce it. You need to leave comment on diff to reproduce. 

I think the problem is next: 

* sticky diff calculates height of diff
* you add new diff comment -> height of diff file increases
* sticky diff behaves like height is old and switch headers too early

**Comment by randx** [comment]
I reverted the feature because I was not able to fix this annoying bug

**Pull request merged**
