### PR TITLE
Tweak issue page a bit 

### PR DESCRIPTION
**Pull request by rumpelsepp**
<del>**I pulled from gitlab.com so there are more commits then I intended to. When master is up to date this pull request should be okay.**
- Include creation time
- Include author without avatar
- Move assignee to the right
- Remove action buttons. IMO they are useless and a bit annoying
- Include comments counter by default, gray it out when there are 0 comments.
- Include opened/closed icons before the title
- Gray out closed issues

screenshot from 2015-03-31 17-14-35

screenshot from 2015-03-31 17-15-51

### CODE REVIEW

**Comment by Razer6** [comment]
Related to #9028

**Comment by rumpelsepp** [comment]
I will rebase in a few minutes after my morning coffe :-)

**Comment by jvanbaarsen** [comment]
@rumpelsepp Nice work! I like the conistency with also showing the 0 comments icon (in lighter gray)

**Comment by rumpelsepp** [comment]
Perfect, thx. :) Rebase is ready. Just out of curiosity: If this pull request gets accepted, the merge request page should be altered accordingly.

**Comment by dblessing** [comment]
Overall I like this change. I like showing the creator/author instead of the assignee on the left. I think you could include a small avatar and it would be OK. 

I'm not sure about only showing the assignee's avatar. I think we need to show the whole name and avatar or don't show it at all. I'm not sure how/where that would be, though.

**Comment by rumpelsepp** [comment]
> I'm not sure about only showing the assignee's avatar.

A don't remember whether there was some information when hovering the avatar. Displaying the whole name and the avatar is overkill I think.

>  I like showing the creator/author instead of the assignee on the left. I think you could include a small avatar and it would be OK.

Personally I think this change turns the issue list into a "fruit salad", especially when you use a lot of tags… This avatar will be shown on every line and its a bit too noise here.

**Comment by dblessing** [comment]
Fair enough :+1:

**Comment by jvanbaarsen** [comment]
@rumpelsepp Im also against showing the avatar :) This is nice and clean! I like it :D

**Comment by dosire** [comment]
Interesting idea's @randx

**Comment by randx** [comment]
@rumpelsepp nice improvements. There are few points from me: 

* tests are broken
* black icons looks too bold taking some unnecessary attention
* what about merge requests page

**Comment by rumpelsepp** [comment]
I just wanted to wait for feedback first before continuing. :)

**Comment by randx** [comment]
@rumpelsepp np :) i like improvements in total

**Comment by jvanbaarsen** [comment]
@rumpelsepp I would really love to see this merged :) Is there anything you need feedback on? Or need help with anything?

**Comment by rumpelsepp** [comment]
Actually I need more time. :( Currently I am on a hard deadline with my master thesis; so unfortunately I can't promise completing this pull request ASAP. Sorry for bringing bad news. :/

**Comment by jvanbaarsen** [comment]
@rumpelsepp No problem :) We wait patiently :)

**Comment by rumpelsepp** [comment]
Revision 2 of my patch series is online:

* Remove "black icon", @randx 
* Adopted my changes to merge requests as well
* Tried to fix tests. I can't reliably run them locally as the fail randomly…

The merge request list lacks support of checkboxes for mass editing (-> consistency). As I don't speak javascript I can't add this myself. See #9160.

**Comment by rumpelsepp** [comment]
screenshot from 2015-04-21 10-33-09

screenshot from 2015-04-21 10-33-29

**Comment by rumpelsepp** [comment]
This test framework stuff is really annoying (sry). It just fails randomly all the time.

``` 
✔  Then I should see +1 in the description                                      # features/steps/shared/note.rb:150
/home/runner/gitlabhq/app/helpers/gitlab_routing_helper.rb:45:in `issue_url': undefined method `namespace' for nil:NilClass (NoMethodError)
	from /home/runner/gitlabhq/lib/gitlab/url_builder.rb:44:in `build_note_url'
	from /home/runner/gitlabhq/lib/gitlab/url_builder.rb:17:in `build'
```

Has nothing to do with my pull request. Locally I get completely different errors.

**Comment by jvanbaarsen** [comment]
@rumpelsepp You can try to stop spring and re-run your test suite: `$ spring stop`. That helps for me sometimes.

**Comment by rumpelsepp** [comment]
Finally, it seems, the build has been successful: https://semaphoreci.com/gitlabhq/gitlabhq/branches/pull-request-9065/builds/6

**Comment by rumpelsepp** [comment]
Ah. Please don't merge it. I have seen a left-over from the first revision which I should remove first. :) I'll ping you then.

**Comment by rumpelsepp** [comment]
It's ready now.

**Comment by randx** [comment]
:+1:

**Pull request merged**
