### PR TITLE
Use full path from root of project.

### PR DESCRIPTION
**Pull request by cmluciano**

### CODE REVIEW

**Comment by dblessing** [comment]
The best thing is that this comment tries to use markdown format in a config file. @drag00n Can you please update the text to remove the markdown syntax? At that point I think it's great to have the full relative path like you've done.

**Comment by drag00n** [comment]
@dblessing How does the latest commit look?

**Comment by dblessing** [comment]
:+1:

**Comment by dblessing** [comment]
Can you please squash the commits then I'll merge.

**Comment by drag00n** [comment]
Squashed, thanks for taking a look at this @dblessing

**Pull request merged**
