### PR TITLE
Update instructions for local backups

### PR DESCRIPTION
**Pull request by gtzinos**
Thank you for taking the time to contribute back to GitLab!

Please open a merge request [on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests), we look forward to reviewing your contribution! You can log into GitLab.com using your GitHub account.

### CODE REVIEW

**Comment by gtzinos** [comment]
Is there someone who check the pull requests ?

**Comment by rymai** [comment]
@gtzinos Thanks for your contribution, but we don't accept pull-requests anymore. Please open a new merge request at https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/new. Thanks in advance!

**Comment by gtzinos** [comment]
Your url is broken

404

The page you're looking for could not be found.

Make sure the address is correct and that the page hasn't moved.

Please contact your GitLab administrator if you think this is a mistake.

**Comment by godfat** [comment]
@gtzinos Sorry, that was meant to create a new merge request based on existing branch. You'll need to login first.

You could also check the project page: https://gitlab.com/gitlab-org/gitlab-ce

The workflow between creating a merge request is mostly the same as creating a pull request. Fork the project, push your branch, and create a merge request. Please let me know if you're unclear how to proceed.

**Comment by gtzinos** [comment]
Thank you @godfat , it is too clear now.

**Comment by rymai** [comment]
@gtzinos Sorry about that! :) Thanks @godfat!

**Comment by gtzinos** [comment]
@rymai No problem, have a great week guys.

**Pull request closed without merging**
