### PR TITLE
show diff in submodules

### PR DESCRIPTION
**Pull request by skv-headless**
screenshot at 28 17-09-06
screenshot at 28 17-09-37

depends on https://github.com/gitlabhq/gitlab_git/pull/37

### CODE REVIEW

**Comment by skv-headless** [comment]
@jvanbaarsen could you take a look?

**Comment by dblessing** [comment]
@skv-headless remind me what this PR does. The submodule commit is already shown in GitLab in last few versions (looks just like the image in the description).

**Comment by skv-headless** [comment]
It's a links on submodules titles, to submodule and revision, like in source tree.

**Comment by randx** [comment]
Looksgood. Thank you

**Pull request merged**
