### PR TITLE
Update version sorter to 2.0.0, fixes #8572

### LINKED ISSUE #8572: The old version of VersionSorter may cause the encoding error in file page.
There is no restriction for the lowest version of VersionSorter in Gemfile, so in current version (1.1.0) it will cause an encoding error when sorting Tags, which turns UTF-8  to ASCII, then trigger a encoding error in file page.

The problem encounter at line #95 in app/helpers/application_helper.rb
https://github.com/Shanicky/gitlabhq/blob/master/app/helpers/application_helper.rb#L95
When we removed the sorting for tags, there is no encoding error in file page

### PR DESCRIPTION
**Pull request by Razer6**
This updates the `version_sorter` gem to 2.0.0. The API is the same, but the implementation improved.
This also includes a fix for encoding. The the current used version, tags get reencoded to ASCII rather than preserving its encoding.

/cc @tsigo

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://razer6-update-version-sorter.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://razer6-update-version-sorter.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by tsigo** [comment]
:+1:

**Comment by Razer6** [comment]
@tsigo Done so. Added a UTF-8 character.

**Comment by jvanbaarsen** [comment]
@Razer6 I've restarted the build in order to see if it becomes green :)

**Comment by Razer6** [comment]
@jvanbaarsen :green_heart:

**Comment by jvanbaarsen** [comment]
@Razer6 Thanks!

**Pull request merged**
