### PR TITLE
C28 ngo37 patch 1

### PR DESCRIPTION
**Pull request by C28NGO37**
Thank you for taking the time to contribute back to GitLab!

Please open a merge request [on GitLab.com](https://gitlab.com/gitlab-org/gitlab/merge_requests), we look forward to reviewing your contribution! You can log into GitLab.com using your GitHub account.

### CODE REVIEW

**Comment by C28NGO37** [comment]
C28NGO37:C28NGO37-patch-1 #10492

**Comment by C28NGO37** [comment]
GODCOIN GDC 
Pubkey Address prefix  r(+0.0010) 
Script Address Prefix o( +0.0010)
Secret Key Prefix X ( +0.0010)


roX  
a (+0.0010)  
n or o (+0.0015) 
a(+0.0010)

*POW*
SHA256d 
6.76

- _

1. 

- [ ] 

_

**Comment by C28NGO37** [comment]
#```

> > GODCOIN GDC
> > Pubkey Address prefix r(+0.0010)
> > Script Address Prefix o( +0.0010)
> > Secret Key Prefix X ( +0.0010)
> > 
> > roX
> > a (+0.0010)
> > n or o (+0.0015)
> > a(+0.0010)
> > 
> > _POW_
> > SHA256d
> > 6.76
> > 
> > * _
> > 
> > 
> > * [ ]
> > 
> > _
> 
> 

```

**Comment by maki-iida** [comment]
`test`

**Pull request closed without merging**
