### PR TITLE
Add task lists to issues and merge requests

### PR DESCRIPTION
**Pull request by mr-vinn**
Make the Markdown parser recognize "[x]" or "[ ]" at the beginning of a list item and turn it into a checkbox input.  Users who can modify the issue or MR can toggle the checkboxes directly or edit the Markdown to manage the tasks.  Task status is also displayed in the MR and issue lists.

This is an accepted suggestion from [feedback.gitlab.com](http://feedback.gitlab.com/forums/176466-general/suggestions/4255282-clickable-task-lists-in-issues-for-sub-tasks-with)
#### TODO
- [x] Write Rspec tests
- [x] Write Spinach tests
- [x] Update documentation
- [ ] Move functionality to a pipeline filter like #7853

### CODE REVIEW

**Comment by eddiemonge** [comment]
This doesn't seem to work in comments on issues

**Comment by sanjayacs** [comment]
-[] create a check box

**Comment by sanjayacs** [comment]
-  [ ] lio9mi

**Comment by sanjayacs** [comment]
-[]

**Comment by sanjayacs** [comment]
-[]

**Pull request merged**
