### PR TITLE
Added a note saying inline HTML is disabled by default

### PR DESCRIPTION
**Pull request by namnatulco**
See #8007.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://namnatulco-master.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://namnatulco-master.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by jvanbaarsen** [comment]
@namnatulco Just to be sure, this PR can only be merged if the PR you refered to has been merged right?

**Comment by namnatulco** [comment]
Quite the opposite! This PR only makes sense if the referred PR is not (yet) merged. The referred PR fixes the problem; this PR writes a note in the documentation saying the problem exists, and how to disable it locally.

I think this PR makes a bit more sense -- in some cases, enabling the interpretation of user-supplied HTML could potentially lead to attacks (which is presumably why it is disabled by default in the first place).

**Comment by jvanbaarsen** [comment]
@namnatulco Thanks :)

**Pull request merged**
