### PR TITLE
Wrong migration order when migrating from 6.x to latest

### PR DESCRIPTION
**Pull request by ZloeSabo**
Im using [upgrade guide](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/update/6.x-or-7.x-to-7.8.md) to upgrade from 6.0 to latest one.

Things went wrong when migrations tried to apply [20140416074002_add_index_on_iid.rb](/gitlabhq/gitlabhq/blob/master/db/migrate/20140416074002_add_index_on_iid.rb) which is removing duplicate issues. 

```
Mysql2::Error: Table 'gitlabhq_production.label_links' doesn't exist: SHOW FULL FIELDS FROM `label_links`/home/soynov/Project/gitlab-development-kit/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `query'
```

As I see this problem is because of invalid schema usage: migration uses latest schema for metadata. 
Current Issue schema includes [Issuable](https://github.com/gitlabhq/gitlabhq/blob/master/app/models/concerns/issuable.rb) concern that specifies label_link relation which should be deleted with corresponded issue. So migration code tries to look up for label_link table.

But there is no such table at that time as it is being created later in [20140729140420_create_label_links.rb](/gitlabhq/gitlabhq/blob/master/db/migrate/20140729140420_create_label_links.rb)

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://zloesabo-fix-missing-label-links-table.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://zloesabo-fix-missing-label-links-table.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by randx** [comment]
This is not ok setting invalid date for migration. It should be other way of fixing it

**Comment by jvanbaarsen** [comment]
@randx Sorry, I missed it was an invalid date, I thought it was just a different date.

**Comment by jvanbaarsen** [comment]
This merge request has been closed because a request for more information has not been reacted to for more than 2 weeks. If you respond and conform to the merge request guidelines in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#pull-requests) we will reopen this merge request.

**Pull request closed without merging**
