### PR TITLE
Fix .container position on navbar

### PR DESCRIPTION
**Pull request by soullivaneuh**
Fixes bootlint [W012](https://github.com/twbs/bootlint/wiki/W012) issue.

### CODE REVIEW

**Comment by jvanbaarsen** [comment]
Thanks

**Comment by randx** [comment]
Reverted because it break mobile UI navbar exapnd. 

Before this fix: 

screenshot 2015-04-29 12 25 13

After: 

screenshot 2015-04-29 12 25 31

**Comment by randx** [comment]
@Soullivaneuh please propose fix that does not break UI

**Comment by Soullivaneuh** [comment]
@randx Maybe something to change on css. But This class configuration can't still as this.

I'll try to fix that.

In which commit did you revert it?

**Comment by Razer6** [comment]
@Soullivaneuh 570594a

**Comment by Soullivaneuh** [comment]
Yes @Razer6, this is **my** commit. :-)

Anyway, found it: https://github.com/gitlabhq/gitlabhq/commit/acad85459fcd9ed7136ecf7327e90bc961544fdf

Will work on this bug.

**Comment by Soullivaneuh** [comment]
@randx navbar mobile tricks is only CSS based or have some JS?

**Comment by Soullivaneuh** [comment]
Ok I think I fixed it, going for PR.

**Pull request merged**
