### PR TITLE
adding avatar to project settings page

### PR DESCRIPTION
**Pull request by Popl7**
as per Feature Request:
http://feedback.gitlab.com/forums/176466-general/suggestions/5433454-add-uploadable-project-icons

an icon / avatar for the project.
Logo can be uploaded or included in the project as png, jpg or gif.
If no logo is present a simple colorful one will be generated.

Done so far:
added avatar removal
show project avatar on dashboard, projects page, project page
added rspec and feature tests
added project avatar from repository
new default project icon added
added copying af avatar to forking of project
added generated icon

TODO:
Test must be checked for completion.
UI must be checked for consistency.
(maybe change the words logo / icon => avatar)

Project page with logo:
screen shot 2014-01-26 at 09 21 27

Project settings with logo:
screen shot 2014-01-25 at 19 53 29

Project settings without logo:
screen shot 2014-01-26 at 21 15 50

Project listing with both uploaded and generated logos:
screen shot 2014-02-26 at 17 39 58

Generated icons when no logo is uploaded:
screen shot 2014-02-26 at 16 06 41
screen shot 2014-02-26 at 17 40 10

### CODE REVIEW

**Comment by 123Haynes** [comment]
@pnull I've picked this up and fixed it a bit.
https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/304

**Comment by pnull** [comment]
@123Haynes great. I would absolutely LOVE this feature. :heart:

**Comment by 123Haynes** [comment]
@pnull This has been merged for 7.8 :)

**Comment by pnull** [comment]
:+1: great. i'm awaiting the 22nd of february more than the 21st (which is my birthday) :-)

**Comment by Viperoo** [comment]
Nice work <3

**Pull request closed without merging**
