### PR TITLE
capitalize URL in "Home page URL"

### PR DESCRIPTION
**Pull request by bbodenmiller**
URL is an acronym and as such should be capitalized

I'm failing to find where else this is defined... can someone point me to the right location?

### CODE REVIEW

**Comment by stanhu** [comment]
You have to modify [this line](https://github.com/gitlabhq/gitlabhq/blob/master/app/views/admin/application_settings/_form.html.haml#L93)

Change the line to:

```
      = f.label :home_page_url, 'Home page URL', class: 'control-label col-sm-2'
```

**Comment by bbodenmiller** [comment]
Should be ready to review now.

**Comment by stanhu** [comment]
Please rebase master, and the tests should pass.

**Comment by bbodenmiller** [comment]
Rebase complete.

**Comment by bbodenmiller** [comment]
@stanhu redid the commit to try and fix the CI issue... looks to be unrelated.

**Pull request merged**
