### PR TITLE
Added search wiki feature

### PR DESCRIPTION
**Pull request by coverer**
As a lot of people requested, I implemented the search in wiki pages.(again), hope this time I followed the style guid and contributing guidlines... 
Refers to:
http://feedback.gitlab.com/forums/176466-general/suggestions/4078088-add-wiki-search-function

Comments:
Since the structure of gitlab has massively improved since the last time, it was now much easier to implement the search feature. I simply added a new filter to project_filter called Wiki which calls the search engine with a new scope 'wiki_blobs'. This is evaluated in ProjectSearchResults, where a new method works straight on the ProjectWiki repository to search files.

New UI:
image

Affected files:
app/controllers/search_controller.rb
app/views/search/_project_filter.html.haml
 lib/gitlab/project_search_results.rb
New file:
app/views/search/results/_wiki_blob.html.haml

### CODE REVIEW

**Comment by s-a** [comment]
@randx  Search the wiki is a killing feature. When will this be merged?

**Comment by vsizov** [comment]
@s-a It's merged 2 years ago (on Sep 9, 2014)

**Comment by s-a** [comment]
hmm i noticed the wiki search does not work on my ce v8.x installation . iam on ubuntu server v16. maybe i need to activate the feature?

**Comment by jvanbaarsen** [comment]
@s-a This should be enabled by default. If you believe this is a bug you can open an issue at: https://gitlab.com/gitlab-org/gitlab-ce

**Pull request merged**
