### PR TITLE
path compare

### PR DESCRIPTION
**Pull request by skv-headless**
_Issue_
http://feedback.gitlab.com/forums/176466-general/suggestions/4300635-option-to-compare-specific-files-directories-in-th
_Depends on_ 
https://github.com/gitlabhq/gitlab_git/pull/19
_Preview_
screenshot from 2013-12-25 17 45 02

### CODE REVIEW

**Comment by lensovet** [comment]
Why was this closed? The feature request is still needed.

**Comment by ZuBB** [comment]
also would like to know why this is closed?

offtop: which BTS is used by gitlab devs as main Github's or their native?

**Comment by jvanbaarsen** [comment]
The original author of this PR did not respond to questions of change. We are a limited team, and we need to focus our resources on active PR's. That's why we have the rule that if the author does not respond withing 2 weeks to questions we need to close the PR. If the author wants to continue working on this PR they can ping one of the core members and we will re-open the PR.

I hope this answers your question.

**Comment by skv-headless** [comment]
I thought that no one need it. I' l try to update it on this week.

**Pull request closed without merging**
