### PR TITLE
use JavaScript instead of CoffeeScript in Views for master

### PR DESCRIPTION
**Pull request by huacnlee**
The reason #9819

@randx 

We need make sure the next changes not happen this case.

Use JavaScript in View not complex than CoffeeScript, and it faster, why not use that?

### CODE REVIEW

**Comment by randx** [comment]
cc @vsizov @tsigo @DouweM

**Comment by DouweM** [comment]
@huacnlee Very good point, thanks! I will try to keep this in mind.

**Comment by vsizov** [comment]
:+1:

**Comment by tsigo** [comment]
Yep, this is a performance thing we need to all be aware of.

That said I don't think we should have _any_ inline Javascript, but that's another battle. :smile:

**Comment by huacnlee** [comment]
https://github.com/gitlabhq/gitlabhq/pull/9959

Please merge #9959 , I need that, our team online GitLab service use 8-3-stable branch

**Comment by tsigo** [comment]
Opened https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/2380 to remove the filters entirely so we don't have to worry about policing this from future contributors.

**Comment by huacnlee** [comment]
@tsigo :+1:

**Pull request merged**
