### PR TITLE
Added support for firing system hooks on group create/destroy and adding...

### PR DESCRIPTION
**Pull request by bladealslayer**
.../removing users to group.

Added tests and updated docs. Also adding 'user_id' field in the hooks for adding/removing user from team.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://bladealslayer-feature-system-hook-for-groups.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://bladealslayer-feature-system-hook-for-groups.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by MrKeiKun** [comment]
:+1:

**Comment by Razer6** [comment]
@bladealslayer Coud you also add a changelog entry?

**Comment by bladealslayer** [comment]
@Razer6 Done.

**Comment by randx** [comment]
Looks good! Thank you

**Pull request merged**
