### PR TITLE
Doc: cronjob should be within user git

### PR DESCRIPTION
**Pull request by artem-sidorenko**

### CODE REVIEW

**Comment by stanhu** [comment]
Looks good to me. @jacobvosmaer, what do you think?

**Comment by jacobvosmaer** [comment]
I think this whole section should be removed, we do not use `whenever` anymore.

**Comment by artem-sidorenko** [comment]
@jacobvosmaer what is the new way to have the CI schedules triggered? I couldn't find anything about this in migration/installation/update docs. As far as I understand https://gitlab.com/gitlab-org/gitlab-ce/issues/2989 it still used

Do I miss something?

**Comment by jacobvosmaer** [comment]
@ayufan can you answer the question above?

**Comment by stanhu** [comment]
Looks like it was removed in 468c355910195. See https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1538.

**Comment by stanhu** [comment]
Superseded by ab72c12028072.

**Comment by artem-sidorenko** [comment]
@stanhu thx!

**Pull request closed without merging**
