### PR TITLE
Add Asana service

### PR DESCRIPTION
**Pull request by j0k3r**
This PR is the following of an other one (which has been closed) #7394 

---

Current state: Ready !
- [x] working asana communication
- [x] ability to restrict to Branch (like the `master`)
#### What does this MR do?

When someone commit with a message including
- "blabla #123456", it will attach a new message to the task 123456 in Asana.
- "fix #456789", it will attach a new message and close (mark as done) the task 456789 in Asana

Also, I've added ability to render `service.help` as markdown. It's more easy to write the help message then.
#### Are there points in the code the reviewer needs to double check?
- `app/models/project_services/asana_service.rb`
- `app/views/projects/services/_form.html.haml`
#### Why was this MR needed?

We use Asana as our Issue tracking system. It will ease the relation between Asana and Gitlab by linking Asana tickets to git commit.
#### What are the relevant issue numbers / Feature requests?

Nope.
#### Screenshots (If appropiate)

From the Gitlab service page:

In Asana:

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://j0k3r-asana.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://j0k3r-asana.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by j0k3r** [comment]
I have one problem left.

I can't save the **Restrict to branch** parameter in the service edition. Whatever I put inside this field, nothing is saved.

To test it, you can go [there](http://j0k3r-asana.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com/h5bp/html5-boilerplate/services/asana/edit) (using default login/pass).

Any help will be welcome :grin:

**Comment by 123Haynes** [comment]
@j0k3r Just a guess, but it looks like you forgot to add the restrict to branch field in services_controller.rb (around line 44)
The api_key field is already in there so that one works.

**Comment by j0k3r** [comment]
@123Haynes Oh yeah, good catch! Thanks. I will try it

**Comment by jvanbaarsen** [comment]
@j0k3r Can you please make sure the items marked by HoundCI are fixed?

**Comment by j0k3r** [comment]
@jvanbaarsen I've fixed HoundCI reports. The build failed but it isn't related to my changes (IMHO).

**Comment by j0k3r** [comment]
@jvanbaarsen It's ok for me :white_check_mark:

**Comment by randx** [comment]
Looks good to me

**Comment by casenjo** [comment]
Sorry to bring this PR back from the dead, I really like this function but I had a question about where it's placed and how to configure it (or maybe there's something I misunderstood).

Right now it appears at the Project Settings > Services level. The problem I see with this is that each user in Asana has their own Personal Access Token. If I were to configure the integration using my token, then when a teammate makes a commit message, the comment that appears on Asana will be added by my account as opposed to the Asana account that corresponds to them.

This looks a little odd, since a specific user is assigned a task in Asana it should (usually) be that same user that fixes and closes the task.

Is this by design? Would I have to create a special user in Asana to be the "commit bot" or did I miss something?

**Comment by randx** [comment]
> Would I have to create a special user in Asana to be the "commit bot" or did I miss something?

@casenjo I am not familiar with Asana but probably you need kind of bot user which will be used to post information.

**Comment by j0k3r** [comment]
Hello @casenjo,
This service work the same way Github handled it: you need an extra user for Gitlab and then use its personal access token. You need to take care of project access on Asana for this user, otherwise, nothing will show up on Asana.

Each action will be performed by this user on Asana (commenting, closing, etc.).
If we choose to use the personal access token for **each** Gitlab user, it'll be a much harder service to build. Also, it'll be harder to check for each user if (s)he has access to the Asana project, etc.

**Pull request merged**
