### PR TITLE
Fix showing overflow when have several items at sidebar

### LINKED ISSUE #8734: Showing Overflow
**Information:**
Whenever you expand setting in a certain project, then you press the `<` to hide the text. For some reasons it display this scroll on the right side of the icons.

**ScreenShots:**
image

### PR DESCRIPTION
**Pull request by duduribeiro**
Fix #8734 

When sidebar have several itens, a scrollbar appears and complicate a little bit the navigation.

_before:_
before

_after:_
after

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://duduribeiro-fix-showing-overflow.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://duduribeiro-fix-showing-overflow.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by randx** [comment]
THank you for fix. But I think reducing padding wont solve the problem. Even with this fix I can just make height of browser window a bit smaller and get scroll again.

**Comment by randx** [comment]
My proposal is hide project navigation when go to settings pages. Ex: 

settings

**Comment by randx** [comment]
In this case it much less chance you have scroll on sidebar

**Comment by duduribeiro** [comment]
@randx, changed liked u proposed :smile: 
pic1
pic2

**Comment by randx** [comment]
@duduribeiro cool. Thank you. I will merge it soon

**Comment by duduribeiro** [comment]
@randx, I have changed the file a little bit to remove the code duplication =)
Thanks =D

**Comment by randx** [comment]
@duduribeiro can you please rebase on master and fix tests?

**Comment by randx** [comment]
There are few failing tests with active tab like

    Project Active Tab :: On Project Settings/Edit :: And the active main tab should be Settings

**Comment by duduribeiro** [comment]
@randx @jvanbaarsen fixed =D

thanks

**Comment by randx** [comment]
@duduribeiro thank you

**Pull request merged**
