### PR TITLE
Add Asana service

### PR DESCRIPTION
**Pull request by j0k3r**
Current state: WIP - Do not merge
- [x] working asana communication
- [x] ability to restrict to Branch (like the `master`)
#### What does this MR do?

When someone commit with a message including
- "blabla #123456", it will attach a new message to the task 123456 in Asana.
- "fix #456789", it will attach a new message and close (mark as done) the task 456789 in Asana

Also, I've added ability to render `service.help` as markdown. It's more easy to write the help message then.
#### Are there points in the code the reviewer needs to double check?
- `app/models/project_services/asana_service.rb`
- `app/views/projects/services/_form.html.haml`
#### Why was this MR needed?

We use Asana as our Issue tracking system. It will ease the relation between Asana and Gitlab by linking Asana tickets to git commit.
#### What are the relevant issue numbers / Feature requests?

Nope.
#### Screenshots (If appropiate)

From the Gitlab service page:

In Asana:

### CODE REVIEW

**Comment by bill008** [comment]
several weeks... two weeks past...

**Comment by dblessing** [comment]
@bill008 the original contributor has not been able to complete the feature yet. You are welcome to take a shot at it if you want this feature sooner.

**Comment by j0k3r** [comment]
@dblessing Could you re-open it? Thanks

**Comment by dblessing** [comment]
I can't reopen this pull request. Is the branch still there? I think if you re-push it will allow me to reopen.

**Comment by j0k3r** [comment]
@dblessing I've rebased it against the master, it should be ok now.

**Comment by j0k3r** [comment]
@dblessing ping?

I've managed (and tested) to restrict message posting to Asana by branch.

I've one thing I can't figure out why it doesn't work and I would like to test it on *TeatroIO* before asking for help :)

**Comment by dblessing** [comment]
Unfortunately it still won't let me reopen. Can you open a new PR and reference this one, please?

**Pull request closed without merging**
