### PR TITLE
Replace CoffeeScript block into JavaScript in Views.

### PR DESCRIPTION
**Pull request by huacnlee**
Use CoffeeScript in View will compile again and again in each requests, because there have variables, Rails view can't caching them.

``` erb
:coffeescript
  projectId = #{@project.id}
```

By my benchmark test for `shared/issuable/_context` render time:
- CoffeeScript: `190ms`
- JavaScript: `19.7ms`

I have enabled all caching config like production environment.

### CODE REVIEW

**Comment by stanhu** [comment]
Fascinating.

/cc: @randx

**Comment by randx** [comment]
> Use CoffeeScript in View will compile again and again in each requests, because there have variables, Rails view can't caching them.

Wow thats amazing. I did not know that.

**Comment by randx** [comment]
Especially benchmarks numbers are big

**Comment by fengmk2** [comment]
:+1:

**Comment by cloudwater** [comment]
awesome!

**Comment by pmq20** [comment]
Saves 10x time. Fascinating!

**Comment by yhl3692319** [comment]
+1

**Pull request merged**
