### PR TITLE
Correct json payload [ci skip]

### PR DESCRIPTION
**Pull request by kzaitsev**
**What does this MR do?**
Fixes json examples

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://bugagazavr-patch-2.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://bugagazavr-patch-2.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by jvanbaarsen** [comment]
@Bugagazavr This matches how the API returns data now?

**Comment by Bugagazavr** [comment]
@jvanbaarsen yep

**Comment by Razer6** [comment]
Verified

**Pull request merged**
