### PR TITLE
Fix merge errors on CHANGELOG

### PR DESCRIPTION
**Pull request by mavimo**
Fixed duplicated string and version on changelog.

### CODE REVIEW

**Comment by jvanbaarsen** [comment]
@mavimo Can you explain why this change is needed? Why did you move the version number?

**Comment by mavimo** [comment]
@jacobvosmaer I removed a duplicate line in 7.10 (unreleased) and i moved the version number from 7.9.3 to 7.9.4 since there is a duplicate version 7.9.3 (see some line below) and we have the 7.9.4 tagged (see  https://github.com/gitlabhq/gitlabhq/blob/v7.9.4/CHANGELOG )

**Comment by jvanbaarsen** [comment]
@mavimo Can you please make this mergeable again?

**Comment by jvanbaarsen** [comment]
This merge request has been closed because a request for more information has not been reacted to for more than 2 weeks. If you respond and conform to the merge request guidelines in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#pull-requests) we will reopen this merge request.

**Pull request closed without merging**
