### PR TITLE
Fixed typo in changelog

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by fgimian** [comment]
+1 looks good

**Comment by jvanbaarsen** [comment]
@forki Can you please make sure this PR is mergeable?

**Comment by jvanbaarsen** [comment]
This merge request has been closed because a request for more information has not been reacted to for more than 2 weeks. If you respond and conform to the merge request guidelines in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#pull-requests) we will reopen this merge request.

**Comment by forki** [comment]
wow. your project has really crazy workflow for fixing a typo ;-)

**Comment by jvanbaarsen** [comment]
@forki If you rebase with master I'll merge tonight :)

**Comment by forki** [comment]
I didn't have a clone of this since I just used github's excellent online edit function.
But I love you guys, so clone it, rebased and pushed again. :heart:

**Comment by jvanbaarsen** [comment]
@forki Thank you so much :heart: :D What is the difference with this line: https://github.com/gitlabhq/gitlabhq/blob/master/CHANGELOG#L120 (sorry I should have asked earlier :( )

**Comment by forki** [comment]
ha someone else has corrected it too. that was probably the cause for the mege conflict.
Sorry.

**Comment by jvanbaarsen** [comment]
@forki Ok, well thanks you for your contribution though :dancers:

**Pull request closed without merging**
