### PR TITLE
Return 204 instead of 404 if no jobs waiting

### PR DESCRIPTION
**Pull request by janten**
See https://github.com/gitlabhq/gitlab-ci/issues/363

### CODE REVIEW

**Comment by janten** [comment]
Any news on this?

**Comment by JulienBlancher** [comment]
+1 would be great :)

**Comment by ayufan** [comment]
I expect it to be resolved in 8.3.

**Comment by JulienBlancher** [comment]
Ok nice thanks !

**Comment by stanhu** [comment]
Should this be closed, @ayufan?

**Comment by ayufan** [comment]
@stanhu Not yet, I want to test it and possibly merge in the upcoming release.

**Comment by janten** [comment]
Any news on this? 8.3 still returns the 404 error.

**Comment by asziranyi** [comment]
@ayufan can you give us a status on this issue? Thanks.

**Comment by cadavre** [comment]
Any info? Why return error on proper check? A must to implement.

**Comment by ayufan** [comment]
@tmaczukin I think that we should be ready to merge this change. Could you verify what consequences it will have for runner older than 0.7, and also previous ruby runner? From what I think it will only lead to failure message printed in logs.

**Comment by tmaczukin** [comment]
@ayufan OK, I will look on this.

**Comment by tmaczukin** [comment]
@ayufan Old ruby runner was looking only for status code `201` (from some version also for `403`) while receiving new builds. Any other status code was causing a message "nothing". So for old ruby runner there is no difference between `204` and `404`.

New runner in go, before version 1.0.0, was looking for more status codes, but any other than `201` was causing only an warning/error message (and for `403` or `clientError` there is also `false` returned from the `GetBuild` method). `204` in case of versions older than 1.0.0 will be matched by `default` in the switch statement, and because of this the message will be an Error 'Checking for builds... failed'. But return of the method will be the same as for `404` code: `return nil, true`.

Since version 1.0.0 status code `204` is caught in parallel with `404` in the switch statement.

**Comment by connorshea** [comment]
Thanks for the contribution to GitLab! Unfortunately we're no longer accepting Pull Requests through the GitHub project.

If you'd like to get this merged, I encourage you to open this as a Merge Request on [the GitLab.com project](https://gitlab.com/gitlab-org/gitlab-ce). Feel free to ping me (@connorshea) and I'll get the right person assigned to it.

Apologies for the troubles, and thanks again for helping improve the project! :heart:

**Pull request closed without merging**
