### PR TITLE
Add support for non-ASCII wiki titles.

### PR DESCRIPTION
**Pull request by Red54**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://red54-master.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by jvanbaarsen** [comment]
We can only accept a merge request if all the tests are green. I've just restarted the build. When the tests are still not passing after this restart and you're sure that is does not have anything to do with your code changes, please rebase with master to see if that solves the issue. Please also fix the item marked by HoundCI

**Comment by jvanbaarsen** [comment]
@Red54 Can you please add at least one test case for this feature? Also please make sure this PR is mergeable. Ping me when ready

**Comment by jvanbaarsen** [comment]
This merge request has been closed because a request for more information has not been reacted to for more than 2 weeks. If you respond and conform to the merge request guidelines in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#pull-requests) we will reopen this merge request.

**Pull request closed without merging**
