### PR TITLE
Fixes #8478. Update timfel-krb5-auth to 0.8.2.

### LINKED ISSUE #8478: dependency on broken timfel-krb5-auth-0.8
The last commit of the project is almost 5 years old.

Building fails, because the linker line is wrong (-lcom_err is missing).

Fixing it seems to be almost impossible, because I don't have much control about what the bundler does.

```
# gem install timfel-krb5-auth -v '0.8'
Fetching: timfel-krb5-auth-0.8.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing timfel-krb5-auth:
	ERROR: Failed to build gem native extension.

    /usr/bin/ruby20 extconf.rb
checking for main() in -lc... yes
checking for krb5_init_context() in -lkrb5... yes
creating Makefile

make "DESTDIR="
compiling ruby_krb5_auth.c
linking shared-object krb5_auth.so
ruby_krb5_auth.o: In function `Krb5_register_error':
ruby_krb5_auth.c:(.text+0x138): undefined reference to `error_message'
collect2: error: ld returned 1 exit status
Makefile:231: recipe for target 'krb5_auth.so' failed
make: *** [krb5_auth.so] Error 1


Gem files will remain installed in /home/jule/.gem/ruby/2.0.0/gems/timfel-krb5-auth-0.8 for inspection.
Results logged to /home/jule/.gem/ruby/2.0.0/gems/timfel-krb5-auth-0.8/ext/gem_make.out
```

### PR DESCRIPTION
**Pull request by limansky**
Fix for build on Gentoo (and other recent systems).

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://limansky-master.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://limansky-master.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by jacobvosmaer** [comment]
@limansky what about going to 0.8.3? Looks like a useful improvement to me https://github.com/timfel/krb5-auth/compare/967fb312384265a4f489a509c0a8fa550888449e...a86ddf2c102a388863f7db99c5597f40ea2ad971

**Comment by limansky** [comment]
@jacobvosmaer Looks good. Seems like the #ifdef block is required for build in old systems.

**Comment by jacobvosmaer** [comment]
@limansky OK. Ping me when you updated the PR?

**Comment by limansky** [comment]
@jacobvosmaer should I create PR for 7.7 as well (or create PR for 7.7 instead of this one)?

**Comment by jacobvosmaer** [comment]
@limansky please target 'master'. Whether or not to apply the change to 7-7-stable is up to the release manager.

**Comment by limansky** [comment]
@jacobvosmaer, I've updated the commit.

**Pull request merged**
