### PR TITLE
Adding tooltip to sidebar. Fix #8738

### LINKED ISSUE #8738: Left nav tooltips for small viewports
With the new UI, certain viewport sizes force the collapse of the left nav, especially on smaller screens. In such cases it's not possible to tell which button is which if you don't already know what the icons mean. It would be really nice to add tooltips to these to tell them apart. It would be even nicer to make those tooltips in the same style as those used in the top nav.

image

### PR DESCRIPTION
**Pull request by duduribeiro**
Before:
tooltip

After
tooltips

`grep has_right_tooltip ./app -R`

```
./app/assets/javascripts/application.js.coffee:  $('.has_right_tooltip').tooltip(placement: 'right', container: 'body')
./app/views/layouts/nav/_dashboard.html.haml:    = link_to root_path, title: 'Home', class: 'shortcuts-activity has_right_tooltip', 'data-original-title' => 'Home' do
./app/views/layouts/nav/_dashboard.html.haml:    = link_to projects_dashboard_path, title: 'Projects', class: 'shortcuts-projects has_right_tooltip', 'data-original-title' => 'Projects' do
./app/views/layouts/nav/_dashboard.html.haml:    = link_to assigned_issues_dashboard_path, title: 'Issues', class: 'shortcuts-issues has_right_tooltip', 'data-original-title' => 'Issues' do
./app/views/layouts/nav/_dashboard.html.haml:    = link_to assigned_mrs_dashboard_path, title: 'Merge Requests', class: 'shortcuts-merge_requests has_right_tooltip', 'data-original-title' => 'Merge Requests' do
./app/views/layouts/nav/_dashboard.html.haml:    = link_to help_path, title: 'Help', class: 'has_right_tooltip', 'data-original-title' => 'Help' do
```

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://duduribeiro-tooltip-sidebar.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://duduribeiro-tooltip-sidebar.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by jvanbaarsen** [comment]
@duduribeiro Looks good! Can you please squash your commits? Ping me when ready

**Comment by duduribeiro** [comment]
@jvanbaarsen fixed =D.. thanks 
[]'s

**Comment by Razer6** [comment]
@duduribeiro Can you rebase. Master has changed and it's not mergable right now.

**Comment by duduribeiro** [comment]
@Razer6 can u check? I thing that I did something wrong :disappointed_relieved: 

thanks

**Comment by duduribeiro** [comment]
@Razer6 do u know why Semaphoer is breaking? 

It's a db error... :disappointed_relieved: 
```
rake aborted!
ActiveRecord::StatementInvalid: PG::Error: ERROR:  relation "issues" does not exist
LINE 5:                WHERE a.attrelid = '"issues"'::regclass
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"issues"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
```

**Comment by jvanbaarsen** [comment]
@duduribeiro What might help is rebasing with master. I'll restart the build as well :)

**Comment by randx** [comment]
Thank you for your contribution. I think it will be cool to have tooltips everywhere - not only on dashboard menu so I pushed similar fix for all navigations to master f989190ed4ea3f9b03451918b55384a2e23fe3af. I will close this PR.

**Comment by duduribeiro** [comment]
\o/
Thanks to all for the help :smile:

**Pull request closed without merging**
