### PR TITLE
Fix the email variable substituation in ssh help page

### PR DESCRIPTION
**Pull request by duduribeiro**
Fixing Issue #7623 to fix the email variable in help page.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://duduribeiro-fix-email-in-ssh-help-page.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://duduribeiro-fix-email-in-ssh-help-page.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by fpgentil** [comment]
:+1:

**Comment by jvanbaarsen** [comment]
@duduribeiro Can you please make sure the items commented on by HoundCI are fixed?

**Comment by duduribeiro** [comment]
@jvanbaarsen fixed =D.. thanks...

**Comment by randx** [comment]
Thank you

**Pull request merged**
