### PR TITLE
Ensure that the first added admin performs repository imports

### PR DESCRIPTION
**Pull request by jvanbaarsen**
This is a fixup from https://github.com/gitlabhq/gitlabhq/pull/9061. I added the changelog entry, so we can merge it in.

/cc @randx

### CODE REVIEW

**Comment by jvanbaarsen** [comment]
Restarted build

**Comment by randx** [comment]
Maybe phantomjs issue. ci.gitlab.com looks green - https://ci.gitlab.com/projects/1?ref=master

**Comment by jvanbaarsen** [comment]
@randx Hm ok, I don't have time right now to look into this. Can you or someone else from BV do that?

**Comment by fgimian** [comment]
Thanks a lot for adding the changelog entry.  Sorry, I've been a little busy on other projects and didn't get to it myself :smile:

**Comment by jvanbaarsen** [comment]
@fgimian No problem :-) Thank you for the contribution ;)

**Comment by randx** [comment]
I will ask someone to look at semaphore

**Comment by jvanbaarsen** [comment]
@randx Thanks :tada:

**Comment by randx** [comment]
@jvanbaarsen can you rebase and merge by yourself please?

**Comment by jvanbaarsen** [comment]
@randx Yeah, was already on my todo list for today!

**Pull request merged**
