### PR TITLE
add CommitNote field expose :created_at

### PR DESCRIPTION
**Pull request by bigsurge**
add CommitNote field expose :created_at

### CODE REVIEW

**Comment by stanhu** [comment]
Thanks, @bigsurge!

**Comment by Razer6** [comment]
@bigsurge Can you also add this to the API documentation??

**Comment by bigsurge** [comment]
@Razer6 Yes, of course, but I do not know where to write API document, can you give me a URL？

**Comment by Razer6** [comment]
The API documentation is here: https://github.com/gitlabhq/gitlabhq/tree/master/doc/api in particular for the commit notes here: https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/commits.md

However, it seems the documentation already says there is a `created_at` field`. So you fixed a bug bay adding that.

**Pull request merged**
