### PR TITLE
Add X-GitLab-Event header for web hooks

### PR DESCRIPTION
**Pull request by kzaitsev**
**What does this MR do?**
This MR adds to all webhooks.
**Are there points in the code the reviewer needs to double check?**
- https://github.com/Bugagazavr/gitlabhq/blob/1957bbb661f423d0454d3a05ac913ea7af99dabe/app/models/hooks/web_hook.rb#L32

**Why was this MR needed?**
This allow filter incoming hooks without parsing payload, similar feature on github https://developer.github.com/v3/activity/events/types/

**What are the relevant issue numbers / Feature requests?**
nil
**Screenshots (if relevant)**
nil

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://bugagazavr-hook-events.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://bugagazavr-hook-events.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by jvanbaarsen** [comment]
@Bugagazavr Can you please make sure this PR is mergeable?

**Comment by Bugagazavr** [comment]
@jvanbaarsen thanks im working on this

**Comment by Bugagazavr** [comment]
@jacobvosmaer ok its done, waiting for tests. Need provide some information in changelog?

**Comment by jvanbaarsen** [comment]
@Bugagazavr Yes please

**Comment by Bugagazavr** [comment]
@jvanbaarsen done, looks like some tests related with "Project Merge Requests" randomly fails, i think this is not related with this PR ( proof: https://semaphoreci.com/gitlabhq/gitlabhq/branches/master/builds/1182 )

**Comment by jvanbaarsen** [comment]
@Bugagazavr thanks

**Comment by Bugagazavr** [comment]
@jvanbaarsen rebased agian

**Comment by vsizov** [comment]
I reverted this PR because it breaks services such as CI integration.

**Comment by Bugagazavr** [comment]
@vsizov so sad, i think i can fix this:

```
class ServiceHook < WebHook
  belongs_to :service

  def execute(data)
    super(data, 'services')
  end
end
```

**Comment by randx** [comment]
@Bugagazavr please fix and submit new PR. If you have some free time - can you also write a test  for broken case?

**Comment by Bugagazavr** [comment]
@randx ok, im try to write additional specs for hooks

**Pull request merged**
