### PR TITLE
Add ace-modes to javascript manifest, fixes #7513

### LINKED ISSUE #7513: GitLab - Getting 404 (Not Found) for /assets/ace/mode-markdown.js
Getting the following error from GitLab while editing the code online.

    GET http://git.server.local/assets/ace/mode-markdown.js 404 (Not Found) application-c8cd2dd87cbf8a023b21baf4d6996ac9.js:26
        t.loadScript application-c8cd2dd87cbf8a023b21baf4d6996ac9.js:26
        t.loadModule application-c8cd2dd87cbf8a023b21baf4d6996ac9.js:26
        setMode application-c8cd2dd87cbf8a023b21baf4d6996ac9.js:27
        (anonymous function)

It seems the asset is requested by the following Javascript that gets inline with the code.

Probably introduced in this commit https://github.com/gitlabhq/gitlabhq/commit/1794f606bd74ae775cd10a3f7da293fb67134c1c

    # gitlab-ce.git/app/views/projects/edit_tree/show.html.haml

    :javascript
      ace.config.set("modePath", gon.relative_url_root + "#{Gitlab::Application.config.assets.prefix}/ace")
      var ace_mode = "#{@blob.language.try(:ace_mode)}";
      var editor = ace.edit("editor");
      editor.setValue("#{escape_javascript(@blob.data)}");
      if (ace_mode) {
        editor.getSession().setMode('ace/mode/' + ace_mode);
      }

I wonder whether the inline Javascript knows anything about Rails asset management, and whether it is assuming that the file would be there in assets folder without hash and all.

### PR DESCRIPTION
**Pull request by Razer6**
##### What does this MR do?

This PR adds most of the modes of ace editor to the javascript manifest. With this PR, there is syntax highlighting while editing a file. I've included all modes which file size is less than 120k.

Additionally it adds syntax highlighting, when creating a new snippet or file via web interface. The mode is determined on the current entered filename and tracks if the user changes it.
##### Are there points in the code the reviewer needs to double check?

Setting asset path of ace modes is removed, since this is now served directly through the rails asset pipeline.
##### Why was this MR needed?

Currently, when opening a file (e.g. a markdown), ace editor tries to load the mode file. Since it's not in the manifest, a 404 error is raised behind the scenes, and no syntax highlighting is available.
##### What are the relevant issue numbers / Feature requests?

This PR fixes
-  #7513
- #6850
- http://feedback.gitlab.com/forums/176466-general/suggestions/6300274-syntax-highlighting-in-editor-while-editing-and-cr

/cc @cirosantilli 
##### Screenshots (If appropiate)

screenshot 2014-08-18 12 24 15

screenshot 2014-08-18 12 26 02

create_file

### CODE REVIEW

**Comment by dblessing** [comment]
@Razer6 I'm closing this for now. We can reopen if you have time to come back to it. Thanks.

**Comment by mpictor** [comment]
@Razer6 Any idea if/when you'll be able to wrap this up? I (and my team) would _really_ like to have syntax highlighting while editing!

I tried to apply these patches to gitlab 7.7, but they don't seem to have an effect...

**Comment by iiSeymour** [comment]
:+1:

**Comment by iiSeymour** [comment]
:+1:  I would also appreciated this functionality.

**Comment by vellamike** [comment]
@Razer6 @dblessing my team and I would really benefit from this.

**Comment by alanteigne** [comment]
:+1:  x 10

**Comment by XVilka** [comment]
Any chance to revive this?

**Comment by kosmiciatakuja** [comment]
Please come back to this issue, this is the only thing stopping my team from moving to gitlab, as we expect a lot of people will be editing files in browser. Thanks!

**Comment by blazeworx** [comment]
1000x this please! Would also love this functionality!

**Pull request closed without merging**
