### PR TITLE
Notification message as broadcast email.

### PR DESCRIPTION
**Pull request by per-garden**
Accidentaly closed https://github.com/gitlabhq/gitlabhq/pull/8309

### CODE REVIEW

**Comment by jvanbaarsen** [comment]
@randx For #8309 you said you need to investigate something. Did you already have time for that?

**Comment by randx** [comment]
@jvanbaarsen nope. So far I see no reason emailing `User.all`.

**Comment by jvanbaarsen** [comment]
@randx Ok thanks for your response. Is the fact that a lot of users are emailed in a batch bothering you? Or the fact that also blocked users are being emailed?

**Comment by randx** [comment]
@jvanbaarsen the fact that we emails all users. I don't know any service that send me email about their maintenance. The concept of broadcast messages does not match with emailing all users for me.

**Comment by jvanbaarsen** [comment]
@randx Ok thanks. @per-garden I'll be closing this PR for now. If you feel that it should be implemented, please open a feedback item on feedback.gitlab.com so we can discuss it there.

**Pull request closed without merging**
