### PR TITLE
Send 500 errors as JSON in the API

### PR DESCRIPTION
**Pull request by jubianchi**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://jubianchi-api-500-json.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://jubianchi-api-500-json.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by jvanbaarsen** [comment]
@jubianchi Does this fix an open issue? Or what is the problem that this is trying to solve?

**Comment by jubianchi** [comment]
@jvanbaarsen it fixes the fact that when gitlab encounters an error it sends unparsable content to the API clients.

**Comment by jubianchi** [comment]
@jvanbaarsen I'll try to do it this week-end ;)

**Comment by jvanbaarsen** [comment]
@jubianchi Ok thanks :) Can you please make sure the tests are passing and the PR is mergeable?

**Comment by jubianchi** [comment]
@jvanbaarsen everything should be ok now ;)

**Pull request merged**
