### PR TITLE
ruby 2.1.6

### PR DESCRIPTION
**Pull request by chulkilee**
https://www.ruby-lang.org/en/news/2015/04/13/ruby-2-1-6-released/

### CODE REVIEW

**Comment by jvanbaarsen** [comment]
@randx Are we going to support ruby 2.1.6? Or skip this one and move right over to 2.2.x?

**Comment by randx** [comment]
@jvanbaarsen we are going to support 2.1.6 in next release. @maxlazio will update omnibus pakage and we will merge this one

**Comment by maxlazio** [comment]
@randx @jvanbaarsen Package has been updated to use 2.1.6, this can be merged

**Comment by randx** [comment]
@maxlazio thank you

**Comment by jvanbaarsen** [comment]
Ok great!

**Pull request merged**
