### PR TITLE
update acts-as-taggable-on

### PR DESCRIPTION
**Pull request by NARKOZ**

### CODE REVIEW

**Comment by maxlazio** [comment]
Any reason why you merged this yourself?

**Comment by NARKOZ** [comment]
@maxlazio sorry, I thought it's a small non-breaking change. Is there anything I could do to help fix it?

**Comment by maxlazio** [comment]
@NARKOZ It is ok, the fix is in place. It might be better in future to mention someone from the rest of the core team to review and merge the MR just so that more people are aware of the changes.

**Comment by NARKOZ** [comment]
@maxlazio thank you, will do from now on.

**Pull request merged**
