### PR TITLE
Refactor, simplify and unify helpers for rendering markup

### PR DESCRIPTION
**Pull request by jirutka**
This PR is closely related to #9288. I’m sending it separately to avoid unnecessary delays with reviewing and merging #9288.

### CODE REVIEW

**Comment by jvanbaarsen** [comment]
I added the Awaiting Feedback label, just so I know we - the core-team - needs to act on this.

**Comment by jirutka** [comment]
Okay, this PR is not ready anyway, one test is failing so I must fix it.

**Comment by jvanbaarsen** [comment]
@jirutka Ok!

**Comment by jirutka** [comment]
@tsigo This PR is now ready, could you please review it?

**Comment by tsigo** [comment]
LGTM, nice refactoring. :+1:

**Comment by jirutka** [comment]
@tsigo This was quick, thanks! :)

**Pull request merged**
