### PR TITLE
Added X-GitLab-Event header for web hooks

### PR DESCRIPTION
**Pull request by kzaitsev**
**What does this MR do?**
- This MR adds to all webhooks.
- Fixes services and more test coverage https://github.com/gitlabhq/gitlabhq/pull/8644

**Are there points in the code the reviewer needs to double check?**
- https://github.com/Bugagazavr/gitlabhq/blob/1957bbb661f423d0454d3a05ac913ea7af99dabe/app/models/hooks/web_hook.rb#L32

**Why was this MR needed?**
This allow filter incoming hooks without parsing payload, similar feature on github https://developer.github.com/v3/activity/events/types/

**What are the relevant issue numbers / Feature requests?**
nil
**Screenshots (if relevant)**
nil

### CODE REVIEW

**Comment by jvanbaarsen** [comment]
cc @vsizov

**Comment by jvanbaarsen** [comment]
@Bugagazavr Thanks for creating a new PR so quickly! :tada:

**Comment by jvanbaarsen** [comment]
I've restarted the failed built.

**Comment by jvanbaarsen** [comment]
@Bugagazavr Can you please make this mergeable?

**Comment by Bugagazavr** [comment]
@jvanbaarsen done

**Comment by jvanbaarsen** [comment]
ping @vsizov

**Comment by vsizov** [comment]
Can you update documentation as well?

**Comment by Bugagazavr** [comment]
@vsizov done

**Comment by vsizov** [comment]
Thank you

**Pull request merged**
