### PR TITLE
Added service API endpoint to retrieve service parameters

### PR DESCRIPTION
**Pull request by bpetheo**
Added service API endpoint to retrive service parameters so automated scripts can get those without any extra configuration.

Related feature request: http://feedback.gitlab.com/forums/176466-general/suggestions/9590679-api-get-slack-parameters
Previous pull request: https://github.com/gitlabhq/gitlabhq/pull/9602

### CODE REVIEW

**Comment by stanhu** [comment]
@bpetheo Thanks for following up. Couple of points:

1. Can you add specs in `spec/requests/services.rb`?
2. Can you update `lib/tasks/services.rake` to auto-generate the documentation for GET?
3. Can you re-run `bundle exec rake services:doc` to generate the new documentation and check that in? 

@Bugagazavr: At the moment, step 3 seems to be failing for me (`NameError: uninitialized constant Service`)

**Comment by Bugagazavr** [comment]
@stanhu i see, try to launch `rake services:doc` without `bundle exec`

**Comment by stanhu** [comment]
@Bugagazavr Yes, I tried that first. Same issue.

**Comment by Bugagazavr** [comment]
it works for me without `bundle exec` in current master, looks like rake task started before rails app initialized

**Comment by Bugagazavr** [comment]
@stanhu found it, should be `task doc: :environment do` instead `task :doc do`

**Comment by stanhu** [comment]
@Bugagazavr Thanks, that did the trick. Submitted a fix here: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1243

**Comment by bpetheo** [comment]
@stanhu I've added the specs and docs you requested. Thanks for your patience.

**Comment by stanhu** [comment]
Looks good. Can you rebase master once more to get pass the failing test and squash this into one commit?

**Comment by bpetheo** [comment]
Done. I hope it can pass the test now.

**Comment by stanhu** [comment]
Thanks, @bpetheo!

**Pull request merged**
