### PR TITLE
Factor can :push_code_to_protected_branches choice  [can be updated]

### PR DESCRIPTION
**Pull request by cirosantilli**
6 lines repeated 7 times.

**Dependencies**
- [x] https://github.com/gitlabhq/gitlabhq/pull/8091 for the DRY `Ability.abilities`

### CODE REVIEW

**Comment by dblessing** [comment]
Looks good to me. @cirosantilli Please rebase once more (sorry).

**Comment by cirosantilli** [comment]
@dblessing updated

**Comment by jvanbaarsen** [comment]
@cirosantilli Im affraid to ask, but can yo uplease rebase? After you did so I'll mark this as ready for merge. Please ping me when ready :) Again, really sorry! Thanks for all the great work :heart:

**Comment by jvanbaarsen** [comment]
This merge request has been closed because a request for more information has not been reacted to for more than 2 weeks. If you respond and conform to the merge request guidelines in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#pull-requests) we will reopen this merge request.

**Pull request closed without merging**
