### PR TITLE
fix disable gavatar can't show issuse avatar

### PR DESCRIPTION
**Pull request by icode**
gavatar disable can not show avatar on issuse

### CODE REVIEW

**Comment by stanhu** [comment]
This breaks other URLs that use `image_tag` or `image_tag`. The correct solution is to use one of those keywords there.

**Comment by icode** [comment]
@stanhu ok, please fix it!

**Comment by jvanbaarsen** [comment]
I think @stanhu was commenting on your code. If you want this to be merged in, please update your PR, otherwise I would need to close without merging.

**Comment by icode** [comment]
@jvanbaarsen I don't know what is wrong with this PR？

**Comment by jvanbaarsen** [comment]
@stanhu Can you guide this PR further?

**Comment by stanhu** [comment]
The issue is that `image_tag` is used in conjunction with `avatar_url` everywhere. Adding `/assets` in `default_avatar` will cause Rails to generate a warning everywhere this happens.

Closing in favor of https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1781.

**Pull request closed without merging**
