### PR TITLE
teamcity basic support

### PR DESCRIPTION
**Pull request by apazdnikov**
FR http://feedback.gitlab.com/forums/176466-general/suggestions/4139027-teamcity-integration

[This is a clone of https://github.com/gitlabhq/gitlabhq/pull/7570, because of a pull request bug.]

Simple Teamcity integration for MergeRequest build status and link on a build.

Algorithm: get status of the last build in Teamcity for concrete Teamcity.BuildConfiguration_ID and MergeRequest.SourceBranch and MergeRequest.Commits.Last
Have to create a build configuration Teamcity.BuildConfiguration_ID to trigger build on each push.
Have to create a survice user and give him viewer-access rights on Teamcity.BuildConfiguration_ID.

Algorithm is very simple but it is working for us since 2014/07/15 and everybody happy :-)

### CODE REVIEW

**Comment by jvanbaarsen** [comment]
@apazdnikov Can you please make sure the tests are passing and the PR is mergeable?

**Comment by apazdnikov** [comment]
Hello.
We've moved all our configurations on https://github.com/gitlabhq/gitlabhq/pull/8439

Is my realization still in demand?

Thank you.

**Comment by jvanbaarsen** [comment]
@apazdnikov Im not really sure what you mean?

**Comment by jvanbaarsen** [comment]
This merge request has been closed because a request for more information has not been reacted to for more than 2 weeks. If you respond and conform to the merge request guidelines in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#pull-requests) we will reopen this merge request.

**Pull request closed without merging**
