### PR TITLE
fix bug 'ActionView::Template::Error (uninitialized constant Gitlab::…

### PR DESCRIPTION
**Pull request by t-zuehlsdorff**
fix bug 'ActionView::Template::Error (uninitialized constant Gitlab::Markdown::AutolinkFilter::Rinku):'

This bug was found when porting GitLab to FreeBSD. Its not possible to display Readme.md or some service templates - Jira for example - without this patch.

### CODE REVIEW

**Comment by rumpelsepp** [comment]
`gemfile.lock` changes are missing

**Comment by t-zuehlsdorff** [comment]
I see, BUT it is not missing. Rinku is already in Gemfile.lock. But not in Gemfile itself!
Also it is registered as dependency of wikicloth, but i could not find it there in the Gemfile nor gemspec.

**Comment by stanhu** [comment]
This test is failing at the moment. You have to run `bundle install` and then check in `Gemfile.lock`.

**Comment by t-zuehlsdorff** [comment]
As already statet the testcase is wrong, not me ;)
But after some updates i could not update this pull request. Please use the new one instead:
https://github.com/gitlabhq/gitlabhq/pull/9609

**Pull request closed without merging**
