### PR TITLE
Add missing color codes for line anchors, fixes #8628

### LINKED ISSUE #8628: Missed some CSS rules in #8425
In my pull request #8425 I missed some CSS rules which are used for highlighting anchors in the source code. IIRC it is this line https://github.com/gitlabhq/gitlabhq/blob/2b10520b306697d7cbae8f3f84ca30cacc821fa4/app/assets/stylesheets/highlight/dark.scss#L15 which is missing in the other themes. I will do a pull request for this in a few days unless no one else is faster than I am. :)

### PR DESCRIPTION
**Pull request by rumpelsepp**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://rumpelsepp-css-fix.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://rumpelsepp-css-fix.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by maxlazio** [comment]
@randx Can you please check if this is something critical to include into the release?

**Comment by randx** [comment]
@rumpelsepp can you please provide a screenshot before/after. Its hard to figure out what it fixes

**Comment by rumpelsepp** [comment]
Sure.

## Before

screenshot from 2015-02-19 20 27 04

## After

screenshot from 2015-02-19 20 27 43

**Comment by randx** [comment]
@rumpelsepp thank you

**Pull request merged**
