### PR TITLE
Call merge request web hook for each commits

### PR DESCRIPTION
**Pull request by baloo**
Execute merge request web hook when new commits comes in the source branch of the merge request.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://baloo-feature-execute-mr-webhooks-upon-commit.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://baloo-feature-execute-mr-webhooks-upon-commit.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by jvanbaarsen** [comment]
@randx What do you think about this?

**Comment by randx** [comment]
I think it is useful for CI tools to get update when you push new code to MR source branch. I think we can accept this. But it needs CHANGELOG item and mention in docs

**Comment by jvanbaarsen** [comment]
@baloo Can you please add Item to CHANGELOG and mention this in the docs? Ping me when ready :)

**Comment by baloo** [comment]
ping @jvanbaarsen 

Tests looks broken in master, I rebased on master so CHANGELOG mention does not merge-conflict. I will rebase on new master once tests are fixed there so everything looks green for this PR.

**Comment by jvanbaarsen** [comment]
@baloo Thanks!

**Comment by baloo** [comment]
ping @jvanbaarsen

**Comment by jvanbaarsen** [comment]
Thanks

**Pull request merged**
