### PR TITLE
add restart commands to github integration

### PR DESCRIPTION
**Pull request by CKGrafico**
People ask me about this two commands to restart and get github integration

### CODE REVIEW

**Comment by jvanbaarsen** [comment]
@CKGrafico This commands are only available when you installed GitLab via omnibus. Can you please add the commands that are used for the source installation?

**Comment by CKGrafico** [comment]
I think that is correct

**Comment by jvanbaarsen** [comment]
@DouweM Do you know if this commands for source installation are correct? We don't have a reconfigure for source right?

**Comment by DouweM** [comment]
@jvanbaarsen Right. The `restart` one is correct, the `reconfigure` one doesn't exist.

**Comment by CKGrafico** [comment]
I saw reconfigure command here https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/README.md

**Comment by jvanbaarsen** [comment]
@CKGrafico Thats the command in omnibus-gitlab. It does exist for that installation type.

**Comment by jvanbaarsen** [comment]
This merge request has been closed because a request for more information has not been reacted to for more than 2 weeks. If you respond and conform to the merge request guidelines in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#pull-requests) we will reopen this merge request.

**Pull request closed without merging**
