### PR TITLE
ugly outlines removed form sidebar

### PR DESCRIPTION
**Pull request by ImanMh**
When you click on sidebar items you an ugly outline appears around each item which does not have a good appearance.

### CODE REVIEW

**Comment by ImanMh** [comment]
Before: 

After: 
screen shot 1394-07-23 at 11 07 37

**Comment by ImanMh** [comment]
Before:
screen shot 1394-07-23 at 11 07 24
After:
screen shot 1394-07-23 at 11 07 37

**Comment by skyruler** [comment]
oh yeah, wait a bit man ;)

**Comment by randx** [comment]
Thanks

**Pull request merged**
