### PR TITLE
Disabled autocapitalize and autocorrect on login field

### PR DESCRIPTION
**Pull request by dvrylc**
**Motive**
I tried logging in on iOS Safari and it kept autocorrecting my username to something that was in the dictionary, and it was pretty annoying. Fixed this by disabling autocapitalize and autocorrect on the login field.

### CODE REVIEW

**Comment by dvrylc** [comment]
Build is failing because master is failing, kindly restart the build when master is fixed :smile:

**Comment by stanhu** [comment]
I'm investigating the build failures. I think they have something to do with the database state not being cleaned properly.

**Comment by stanhu** [comment]
Can you rebase master and try again?

**Comment by stanhu** [comment]
Somehow this pull request is picking up changes in other commits. Can you rebase and squash?

**Comment by dvrylc** [comment]
Whoops looks like I messed up the commits a little, should be fixed now. Let's wait for the build to pass! :grinning:

**Comment by stanhu** [comment]
@dvrylc Thanks!

**Comment by dvrylc** [comment]
@stanhu Glad to help!

**Pull request merged**
