### PR TITLE
[bugfix] Merge request diff view behaviour fix

### PR DESCRIPTION
**Pull request by SSPkrolik**
Fixed 'back button' bug in merge request view.

Steps to reproduce:
1) Open merge request view page at a URL like this: http://localhost:3000/gitlab-org/gitlab-test/merge_requests/3/diffs on "Discussion" tab
2) Click on 'Changes' tab
3) Click 'View file @ rev-number' button
4) Click 'BACK' browser button

Expected result:
User moves back to the diff page

Actual result:
User is moved to the diff page which is shown as a plain json diff document, because browser has cached the last AJAX-call of `loadDiff` coffee-script method.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://zeoalliance-merge-request-diff-view-fix.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://zeoalliance-merge-request-diff-view-fix.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by Razer6** [comment]
I cannot reproduce this on the following MR: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/340

**Comment by SSPkrolik** [comment]
@Razer6 I've tried, and I could. The mandatory condition is to first load page on discussion tab, then move to `Changes` tab to get diff loaded with ajax, then click on 'view file @ ' button, and then 'browser's back button'. It is reproduced on Ubuntu+Chrome, and OSX+Safari

**Comment by Razer6** [comment]
@SSPkrolik I cannot reproduce

1. Go to https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/340
1. Go to https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/340/diffs
1. Go to `View  file @ c13dcc4` on the first file

This works as expected

**Comment by yglukhov** [comment]
I can also reproduce it. This seems to be a browser specific caching issue. Safari, Firefox and Chrome behave differently on Mac and Linux and respect ETag header differently. Clicking back in Safari does not reload the cached page, if no ETag was set. Running gitlab on localhost does not produce ETags, and that is why this issue is also setup-dependant. Chrome, on the other side, seems not to respect ETags on Linux at all, and the issue is reproducible with @Razer6 's steps. This PR really seems to fix it.

**Comment by randx** [comment]
Cool. Lets merge this one

**Comment by yglukhov** [comment]
:thumbsup:

**Pull request merged**
