### PR TITLE
Update 7.6-to-7.7.md

### PR DESCRIPTION
**Pull request by robotroll**
Fix link to gitlab.yml.example in paragraph 5

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://robotroll-patch-1.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://robotroll-patch-1.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by jvanbaarsen** [comment]
We can only accept a merge request if all the tests are green. I've just restarted the build. When the tests are still not passing after this restart and you're sure that is does not have anything to do with your code changes, please rebase with master to see if that solves the issue.

**Comment by robotroll** [comment]
Hey,
thanks for your feedback. I can't understand why the test is failing since I only changed one line in the documentation. I'll rebase with master and try the tests again.

**Comment by robotroll** [comment]
I'm not sure if I did this right. Was my first rebase...

**Comment by jvanbaarsen** [comment]
Thanks!

**Pull request merged**
