### PR TITLE
Rename API::APIHelpers -> API::Helpers;

### PR DESCRIPTION
**Pull request by huacnlee**
Rails Autoload find file to require is use , APIHelpers -> api_helpers.rb, not helpers.rb;

### CODE REVIEW

**Comment by stanhu** [comment]
:+1: @randx, any issues with this?

**Comment by randx** [comment]
:+

**Comment by Razer6** [comment]
@randx this was merged into 8-0-stable!

**Comment by randx** [comment]
@Razer6 oops. I did not notice. Thanks! I revert this one. 


@huacnlee can you re-submit this to master?

**Comment by huacnlee** [comment]
I will do that after 8 hours later, currently sleeping time (China).
But why not merge it into 8.0, 8.1?

**Comment by randx** [comment]
@huacnlee cool

> But why not merge it into 8.0, 8.1?

we don't merge refactoring in stable branches.

**Pull request merged**
