### PR TITLE
[wip] Started on the actual rspec 3 upgrade

### PR DESCRIPTION
**Pull request by jvanbaarsen**
Can't get spinach test to be green since I've upgraded the rspec gem. When rspec was at 2.99 all was green, now a lot of red tests.

If anyone has a clue on what this can be, please let me know. I already contacted the guys behind Spinach in this Twitter thread: https://twitter.com/jvanbaarsen/status/565994482978390016

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://jvanbaarsen-road-to-rspec-3.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://jvanbaarsen-road-to-rspec-3.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by NARKOZ** [comment]
Update capybara gem https://github.com/jnicklas/capybara/blob/master/History.md#version-230

**Comment by jvanbaarsen** [comment]
@NARKOZ Ok thanks, I'll give it a shot later this week!

**Comment by jvanbaarsen** [comment]
Just a small update:

I have updated Capybara, this fixed a lot of rspec 3 compatibility issues. Now I need to go over all the broken specs since there are some naming conflicts in rspec - capybara.

**Comment by jvanbaarsen** [comment]
Stil working on this.

**Comment by tsigo** [comment]
@jvanbaarsen What can I help with? Have you pushed your latest work to this branch? At this point it's been so long that I'm worried about merge conflicts being so much trouble that it might be worth starting over.

**Comment by jvanbaarsen** [comment]
@tsigo I'll rebase with master today. I'll let you know.

**Comment by jvanbaarsen** [comment]
@tsigo I just rebased, only conflicts were in Gemfile..

**Comment by jvanbaarsen** [comment]
@tsigo I'll give you access to my fork, that way we can work on this together, ok?

**Comment by jvanbaarsen** [comment]
I'm not 100% sure, but it looks like I ran into a bug with Poltergeist: https://github.com/teampoltergeist/poltergeist/issues/624

**Comment by jvanbaarsen** [comment]
@tsigo Thanks :)

**Comment by jvanbaarsen** [comment]
@tsigo Shall I close this PR so we can continue work on the MR on gitlab.com?

**Comment by tsigo** [comment]
@jvanbaarsen If you can push to that branch on gitlab.com, sure.

**Comment by jvanbaarsen** [comment]
@tsigo Im not really sure, have to check :)

**Comment by jvanbaarsen** [comment]
This has been merged on gitlab.com (Thanks @tsigo :yellow_heart: :green_heart: )

**Pull request closed without merging**
