### PR TITLE
Add Atlassian Bamboo service

### PR DESCRIPTION
**Pull request by dblessing**
# What does this MR do?

Adds support for Atlassian Bamboo as a CI service.

This also includes documentation in `doc/project_services`. There are some 'gotchas' when setting up triggers with Bamboo. It doesn't support nice webhooks like GitLab CI.
# Are there points in the code the reviewer needs to double check?

I think this will cause a merge conflict with enterprise edition. If so, it will be in the `app/views/projects/services/_form.html.haml` file and is easily resolvable.

I'm also questioning whether we want line 31 changes in `app/views/projects/services/_form.html.haml`. 

You'll probably notice that I listed all services in the new 'Project Services' documentation page but only wrote docs for Bamboo service. It might be ideal to have docs for all services, but that's outside the scope of this PR. I can probably go back and write some other service docs, or someone else can, too.
# Why was this MR needed?

We want to use Bamboo as a CI service and it was simple to add. I'm certain others would find use, also.
# What are the relevant issue numbers / Feature requests?

None that I'm aware of.
# Screenshots
## Project Services help page

screen shot 2014-10-16 at 2 24 46 pm
## Bamboo help page

screen shot 2014-10-16 at 2 24 52 pm

### CODE REVIEW

**Comment by bentolor** [comment]
@dblessing Thanks for contributing this implementation. 

I have a small issue in our environment: Bamboo requires credentials to accept the build trigger. From reading the code this service seems to GET [https://bamboohost/bamboo/updateAndBuild.action?buildKey=PROJ-KEY](https://bamboohost/bamboo/updateAndBuild.action?buildKey=PROJ-KEY) to trigger the build. 

This is not sufficient for our Bamboo installation (5.7.2 w/ Crowd): It redirects to the Login page. 

Appending `&os_authType=basic` and providing the credential works as basic auth params.

I'm foreign to Ruby, but I guess a simple Copy & Paste of the [code block in `build_info(sha)`](https://github.com/gitlabhq/gitlabhq/commit/93bed4435e9e61570dd27e1660c230c3c323a744#diff-9aa8169ccafcf0ea06afa51130ab53eaR54) to `execute(_data)` would fix this for and not cause any troubles for others?

**Comment by dblessing** [comment]
yes, what you say seems like it will work. Would you like to issue a pull request?

**Comment by bentolor** [comment]
@dblessing, Thanks for your quick response. I'll try my best & report back.

**Comment by bentolor** [comment]
@dblessing The change worked and I submitted a pull request.

I have one issue: Calling `#{bamboo_url}/rest/api/latest/result?label=#{sha}` against Bamboo 5.7.2 returns only results for master build results, not any branch results. 

The official [Bamboo REST API documentation](https://docs.atlassian.com/bamboo/REST/5.7.1/#d2e616) mentions sth. about _"Provide list of latest build results for *top level plans*"_. 

Does this work for you and in which environment?

**Comment by bentolor** [comment]
I have contacted the Atlassian Support: The current feedback is is follows:

> Upon further checking, the /rest/api/latest/result endpoint only display latest results from the main plans and not branch plans. 

Given this I wonder how this worked for you at all, because Merge Requests _are_ branches which would be reflected in Bamboo branch plans. 

I'm really puzzled.

**Comment by dblessing** [comment]
@bentolor I am puzzled by that news as well. I am quite certain it worked at the time I wrote it. I must admit that I have no used it recently, though. I can try to test when I get a chance. We are still on 5.6.x.

**Comment by bentolor** [comment]
For reference: A related issue was already reported on Gitlab: https://gitlab.com/gitlab-org/gitlab-ce/issues/1355

**Pull request merged**
