### PR TITLE
issue page right-side pannel scroll issue fixed

### PR DESCRIPTION
**Pull request by baladkb**
Hi @rymai, 
I fix this https://gitlab.com/gitlab-org/gitlab-ce/issues/13497 issue,
please check...

### CODE REVIEW

**Comment by baladkb** [comment]
@Razer6 @jschatz1  did you had a time to check my commit ?

**Comment by jschatz1** [comment]
@baladkb So you are saying we want `overflow:hidden` because we are now using jQuery `niceScroll` on the sidebar?

**Comment by baladkb** [comment]
Yes @jschatz1 
because of this below issue,
 
issue

**Comment by vicvega** [comment]
:+1: 
same issue here
with firefox 44.0.2 on ubuntu 14.04

**Comment by rymai** [comment]
@baladkb @vicvega Do you still experience this issue with GitLab 8.5.0?

**Comment by vicvega** [comment]
no more

it's fixed in 8.5

thanks

**Comment by rymai** [comment]
@vicvega Great to hear that! @baladkb If you confirm, please close this issue. Thanks!

**Comment by baladkb** [comment]
Thanks @vicvega and @rymai 

@rymai I am going to test it soon..

**Comment by baladkb** [comment]
@rymai 
I checked "GitLab 8.5.0-rc1" but still issues appearing, I think issue solved in "VERSION for 8.6.0-pre".

**Comment by vicvega** [comment]
@baladkb try the latest version (8.5.1)
I see the issue already fixed in 8.5.0 (I mean the stable version, not release candidate)

**Comment by baladkb** [comment]
@vicvega 
I updated the Git-Lab to 8.5.2 and this issue fixed, now its working fine.

Thanks @all(@rymai , @vicvega , @Razer6, @jschatz1).

**Pull request closed without merging**
