### PR TITLE
Only load byebug on MRI

### PR DESCRIPTION
**Pull request by yorickpeterse**
With this Gem only loading on MRI at least the `bundle install` process works on Rubinius. Whether the application itself will run is something I have yet to take a look at.

### CODE REVIEW

**Comment by dosire** [comment]
@tsigo Can you merge this? Looks legit to me and would be nice to have Rubinius work better. /cc @randx

**Comment by tsigo** [comment]
Away from home today but will do when I get back tonight.

**Comment by dosire** [comment]
Thanks @tsigo

**Comment by tsigo** [comment]
@YorickPeterse Could you please update this so that it's using the Ruby 1.9 Hash syntax? Then we'll be good to merge.

Thanks!

**Comment by YorickPeterse** [comment]
@tsigo Done!

**Comment by tsigo** [comment]
@YorickPeterse Thanks!

**Pull request merged**
