### PR TITLE
No need to check if `repository_ref` is present

### PR DESCRIPTION
**Pull request by ghost**
There is no need to check if `repository_ref` is present as:

```
@repository_ref = if repository_ref.present?
                    repository_ref
                  else
                    nil
                  end
```

is as same as doing:

```
@repository_ref = repository_ref
```

### CODE REVIEW

**Comment by zenati** [comment]
This MR has been transfered to https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/784.

**Comment by stanhu** [comment]
Is that true? If `repository_ref` is `""`, then `@repository_ref` will be `nil` in the original case, whereas it will be `""` in the new case. It may be worthwhile to check how it's being used.

**Comment by DouweM** [comment]
@stanhu is right. There's also most likely a reason why the check was added. 

@zenati please double check that this doesn't break (or otherwise change) expected behavior.

**Comment by jvanbaarsen** [comment]
@DouweM Hm ok, overlooked this (Also build was green). Shall I revert? Or wait for @zenati to double check?

**Comment by DouweM** [comment]
@jvanbaarsen Revert, please. The repository_ref seems to originate in a param, so it could very well be an empty string, in which case we want to treat it as nil.

**Comment by Razer6** [comment]
Maybe add a regression test to catch this behaviour.

**Comment by jvanbaarsen** [comment]
@Razer6 :+1: for regression test

**Comment by stanhu** [comment]
MR for the test here: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/788

**Pull request merged**
