### PR TITLE
Show assignees in the merge-requests index

### PR DESCRIPTION
**Pull request by KelvinMutuma**
/cc @dosire Changed authored by text to assigned to in the issues merge requests index. This is item 2 in [this issue](http://feedback.gitlab.com/forums/176466-general/suggestions/6428440-option-to-have-work-in-progress-filter-for-issues)

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://kelvinmutuma-show-assignees-in-merge-requests-index.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://kelvinmutuma-show-assignees-in-merge-requests-index.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by dosire** [comment]
Thanks @KelvinMutuma 

If you have time maybe you can add screenshots of the before and after situation, I forgot to mention that in our call.

**Comment by KelvinMutuma** [comment]
/cc @dosire 
This is the image before the commit..which shows merge requests 'authored by' assignee

before

This is the image after the commit showing the issue/issues 'assigned to' assignee

after

**Comment by dosire** [comment]
Thanks @KelvinMutuma 

@randx can you review this?

**Comment by randx** [comment]
@KelvinMutuma Thank you!

**Comment by dosire** [comment]
The core team decided to remove the 'Work in Progress' listing. https://gitlab.com/gitlab-org/gitlab-ce/commit/155b2d46ae19bebeb9b40794fb9b2e3f6e3ab993

**Comment by randx** [comment]
I am ok with core team decision

**Comment by KelvinMutuma** [comment]
@dosire I have checked .. a request is either assigned or unassigned

**Comment by dosire** [comment]
@KelvinMutuma yes, that's right

**Pull request merged**
