### PR TITLE
Added support for firing system hooks on group create/destroy and adding...

### PR DESCRIPTION
**Pull request by bladealslayer**
.../removing users to group.

Added tests and updated docs. Also adding 'user_id' field in the hooks for adding/removing user from team.

### CODE REVIEW

**Comment by 123Haynes** [comment]
@bladealslayer Are you still planing on working on this? If not i'll pick it up :)

**Comment by bladealslayer** [comment]
@123Haynes ah, yes, thanks for the reminder :) I'll rebase and fix this up.

**Comment by 123Haynes** [comment]
great :)

**Comment by bladealslayer** [comment]
New PR: #8652. Hope hounds checks pass this time :)

**Pull request closed without merging**
