### PR TITLE
[WIP] Use rails-bootstrap-forms gem for form rendering

### PR DESCRIPTION
**Pull request by soullivaneuh**
This PR is related to #8470.

The goal is to use `rails-bootstrap-form` gem to simplify form rendering on bootstrap.

To do:
- [x] Install rails-bootstrap-form gem
- [ ] Rewrite all form rendering with bootstrap-form helpers (**admin section only** for the moment, next with another pull requests)
- [ ] Wait for `btn-group` forms management: bootstrap-ruby/rails-bootstrap-forms#132
- [ ] Wait "HTML help block" issue answer: https://github.com/bootstrap-ruby/rails-bootstrap-forms/issues/211. Concern those forms:
  - https://github.com/gitlabhq/gitlabhq/blob/master/app/views/admin/applications/_form.html.haml#L17-L21
- [ ] Wait "Static control without label" issue answer: https://github.com/bootstrap-ruby/rails-bootstrap-forms/issues/212. Concern those forms:
  - https://github.com/gitlabhq/gitlabhq/blob/master/app/views/admin/broadcast_messages/index.html.haml#L14-L20
- [ ] Wait "Unwanted space with hide_label option on inline form" answer: https://github.com/bootstrap-ruby/rails-bootstrap-forms/issues/214. Concern those forms:
  - https://github.com/gitlabhq/gitlabhq/blob/master/app/views/admin/groups/show.html.haml#L61-L67
  - https://github.com/gitlabhq/gitlabhq/blob/master/app/views/admin/users/index.html.haml#L24-L28
- [ ] Wait "Unwanted hidden input on check_box helper with bootstrap_form_tag" answer: https://github.com/bootstrap-ruby/rails-bootstrap-forms/issues/215. Concern those forms:
  - https://github.com/gitlabhq/gitlabhq/blob/master/app/views/admin/projects/index.html.haml#L6-L24
- [ ] Wait "Ability to create radio button without label?" answer: https://github.com/bootstrap-ruby/rails-bootstrap-forms/issues/161. Concern those forms:
  - https://github.com/gitlabhq/gitlabhq/blob/master/app/views/admin/services/_form.html.haml
- [ ] Fix weird css issue: https://github.com/gitlabhq/gitlabhq/pull/9055#issuecomment-88881347
- [ ] Fix bad visibility form rendering on application settings: https://github.com/gitlabhq/gitlabhq/pull/9055#issuecomment-120387485
- [ ] Add some notes on UI best practices documentation [form_for / form_tag / alert_messages / f.primary]
- [ ] All tests should be green
- [ ] Update CHANGELOG file

Pending questions:
- Should we remove `.form-fieldset` class and add padding by default on `fieldset` element?
- Is the new form error rendering correct?
- Can Rubocop have custom rules detection? Could be useful to have a `form_for` usage detection, isn't it? (make `bootstrap_form_for` required. Use `text_field_without_bootstrap` is necessary)
- Should I use static control field for special subforms? (https://github.com/gitlabhq/gitlabhq/pull/9055#issuecomment-87835413)
  - No, use `form_group` instead.
- OK for using required label css trick? (https://github.com/gitlabhq/gitlabhq/pull/9055#issuecomment-89258863)

Externals links:
- https://github.com/bootstrap-ruby/rails-bootstrap-forms

Please tell me if I have some other task to do on this subject.

Thanks.

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
I saw that sometime `.form-fieldset` is used just to add some margin on fieldset.

Code: https://github.com/gitlabhq/gitlabhq/blob/master/app/assets/stylesheets/generic/forms.scss#L84-L86

Why not put this margin by default on fieldset?

**Comment by Soullivaneuh** [comment]
Can't convert btn-group to bootstrap-form at the moment because it's not managed.

Example here: https://github.com/gitlabhq/gitlabhq/blob/master/app/views/admin/application_settings/_form.html.haml#L45-L52

Issue opened, waiting for news: https://github.com/bootstrap-ruby/rails-bootstrap-forms/issues/132

**Comment by Soullivaneuh** [comment]
Got weird form rendering on validation error, like this:

bootstrap_form_error

Have to be fixed.

**Comment by Soullivaneuh** [comment]
Invisible fields on error is due to [this overridden variable](https://github.com/gitlabhq/gitlabhq/blob/master/app/assets/stylesheets/base/gl_variables.scss#L96) used by `.has-error` text color.

But If I disable it, alert text-color are not white anymore.

Any suggestion?

**Comment by Soullivaneuh** [comment]
Fixed. Now we have this:

bootstrap_form_error

Sounds good for you?

**Comment by Soullivaneuh** [comment]
Can Rubocop have custom rules detection? Could be useful to have a `form_for` usage detection, isn't it?

**Comment by randx** [comment]
> The goal is to use rails-bootstrap-form gem to simplify form rendering on bootstrap.

Looks awesome. code looks clean

**Comment by Soullivaneuh** [comment]
Yes @randx I think so too.

The less code you have to do, the happier developer you will be.

A good developer is a lazy developer, remember that! ;) :+1:

**Comment by Soullivaneuh** [comment]
Just made group forms.

Have to use `f.static_control` for avatar and alerts but it renders quite differently:

gitlab_group_edit_static_padding

Not the same padding on avatar form because of `<p>` static control, and alerts are quite separated.

What do you think? Don't know for the moment if I can do better with this lib. Any suggestion?

**Comment by randx** [comment]
I am not sure I understand :)

**Comment by Soullivaneuh** [comment]
What did you not understand @randx? Surely by mad english... ;)

**Comment by Soullivaneuh** [comment]
Find a way to fix that. Use `form_group` instead of `static_control` for sub forms.

**Comment by Soullivaneuh** [comment]
Got some UI issue on inline form without label.

See related created issue: https://github.com/bootstrap-ruby/rails-bootstrap-forms/issues/214

**Comment by randx** [comment]
@Soullivaneuh cool. I didnt understand what padding you talked about. But does not matter - glad you managed to fix it

**Comment by Soullivaneuh** [comment]
Got some strange html render with checkbox tag (not form_for).

Issue created: https://github.com/bootstrap-ruby/rails-bootstrap-forms/issues/215

**Comment by Soullivaneuh** [comment]
Just updated admin projects filters but got strange results:

gitlab_projects_filters

Could be custom css fault?

**Comment by Soullivaneuh** [comment]
Just updated admin service templates.

Was this before: 

gitlab_hipchat_before

And after:

gitlab_hipchat_after

Seems good for you?

Please not the double "Active" label. On issue is pending about that here: https://github.com/bootstrap-ruby/rails-bootstrap-forms/issues/161

**Comment by Soullivaneuh** [comment]
Just updated the admin users form.

I also taken profit to introduce the required label css tricks: https://github.com/bootstrap-ruby/rails-bootstrap-forms#required-fields

This will add a `*` on every required form.

So we turn the old manual `* required` text like this:

gitlab_admin_user_before

To this:

gitlab_admin_user_after

More cleaner isn't it? :+1: 

More cooler, this will be automatically applied on every required field of each form using `bootstrap_form_(tag|form)`.

Are you OK with this?

You can see the related edited css here: https://github.com/gitlabhq/gitlabhq/pull/9055/files#diff-8173fb057f92d7588e1800c179fe111cR46
And a field example here: https://github.com/gitlabhq/gitlabhq/pull/9055/files#diff-583833dd037fc513229f947d3467c520R7

Regards.

**Comment by randx** [comment]
Cool!

**Comment by randx** [comment]
@Soullivaneuh i am a bit afraid that PR will be hard to complete and review since it touches every single form in application. Maybe we can do it step by step converting several forms per PR?

**Comment by Soullivaneuh** [comment]
@randx What is your suggestion? Section by section? Could be possible unless for shared forms templates.

I nearly finish admin section, 69 forms has not be reviewed yet but in general it's just basic form.

The idea of separate PRs sounds go but could be difficult because of the lot of external issue and linked deps.

It's why I'm forcing to keep the list of questions/todo updated on this PR. :+1:

**Comment by randx** [comment]
@Soullivaneuh my suggestion is section by section

**Comment by Soullivaneuh** [comment]
@randx OK for me. I'm nearly finish the admin section and some shared templates.

I propose to finish this PR to get the base of bootstrap form plus the admin section.

When this PR will be finished and stable, we can merge it and start another, section by section.

Sounds good for you?

**Comment by randx** [comment]
@Soullivaneuh sounds like a plan :)

**Comment by jvanbaarsen** [comment]
@Soullivaneuh I like the small tweaks this PR brings to the UI :) Great job so far!

**Comment by Soullivaneuh** [comment]
The admin section is completely rewritten but some rails-bootstrap-forms issues still have to be resolved before merge this PR.

So I'm blocked for continuing.

@randx Maybe another solution. Keep continue the integration of another sections on this PR but with one commit by section. With this method, you could see and review the change section by section just by clicking to the concerned commit.

If you find this interesting, I can setup a demo of my PR for easier reviewing.

What do you think?

Regards.

**Comment by randx** [comment]
> Keep continue the integration of another sections on this PR but with one commit by section

@Soullivaneuh I want to merge reviewed parts so I propose you just create another PR on top of this branch with next section. When I merge this one - it will be only uniq changes per section in next PR

> If you find this interesting, I can setup a demo of my PR for easier reviewing.

thank you. I think its not needed - I will use localhost to check

**Comment by randx** [comment]
So try to fix tests here and prepare it for review before starting new section

**Comment by Soullivaneuh** [comment]
@randx 

> So try to fix tests here and prepare it for review before starting new section

Yes will do that.

After this, I will separate section by subPRs directly on my form. With that, you could review it easily.

After review, I'll just have to merge all my subPR and then, this one.

This method will be easier for me if I have to modify the main branch.

Are you OK for that?

**Comment by Soullivaneuh** [comment]
I can't run test on my local, got the following error:

```
  Scenario: I change my code preview theme
    ✔  Given I sign in as a user                                       # features/steps/shared/authentication.rb:7
    ✔  Given I visit profile design page                               # features/steps/shared/paths.rb:126
    ✔  When I change my code preview theme                             # features/steps/profile/profile.rb:121
    ✔  Then I should receive feedback that the changes were saved      # features/steps/profile/profile.rb:132
/home/sullivan/.rvm/gems/ruby-2.1.3/gems/activerecord-4.1.9/lib/active_record/connection_adapters/postgresql/database_statements.rb:128:in `exec': PG::Error: ERROR:  deadlock detected (ActiveRecord::StatementInvalid)
DETAIL:  Process 22429 waits for AccessExclusiveLock on relation 17755 of database 16385; blocked by process 22447.
Process 22447 waits for AccessShareLock on relation 17562 of database 16385; blocked by process 22429.
HINT:  See server log for query details.
: TRUNCATE TABLE "application_settings", "broadcast_messages", "deploy_keys_projects", "emails", "events", "forked_project_links", "identities", "issues", "keys", "label_links", "labels", "members", "merge_request_diffs", "merge_requests", "milestones", "namespaces", "notes", "oauth_access_grants", "oauth_access_tokens", "oauth_applications", "project_import_data", "projects", "protected_branches", "services", "snippets", "subscriptions", "taggings", "tags", "users", "users_star_projects", "web_hooks" RESTART IDENTITY CASCADE;
```

Any idea?

**Comment by rumpelsepp** [comment]
Run it again. :)
Currently it's a bit buggy. I struggled with the same problem a few days ago: https://github.com/gitlabhq/gitlabhq/pull/9184#issuecomment-95863386

**Comment by jvanbaarsen** [comment]
@Soullivaneuh Are you still working on this?

**Comment by Soullivaneuh** [comment]
@jvanbaarsen Yes.

Sorry I have not lot of time at this moment (apartment search). I think I will go back actively on this PR in two weeks maximum.

Regards.

**Comment by maxlazio** [comment]
Good luck with your search!

**Comment by tsigo** [comment]
Personally I'd prefer [simple_form](https://github.com/plataformatec/simple_form) using its Bootstrap-specific initializer. That way we're less tightly coupled to Bootstrap for the future.

**Comment by Soullivaneuh** [comment]
`simple_form`  seems to be less complete. For sample, I don't see on the doc how to set an horizontal or vertical form.

BTW I already changed a lot of template. I would prefer to keep it as is unless other collaborators wants to change too.

**Comment by jvanbaarsen** [comment]
@Soullivaneuh I believe @randx agreed on this approach, so I think you can continue this way :)

**Comment by tsigo** [comment]
> For sample, I don't see on the doc how to set an horizontal or vertical form.

It's part of the Bootstrap initializer: https://github.com/plataformatec/simple_form/blob/master/lib/generators/simple_form/templates/config/initializers/simple_form_bootstrap.rb

**Comment by jvanbaarsen** [comment]
@randx What do you think? I would propose to continue the way @Soullivaneuh has already been taken. The argument from @tsigo "That way we're less tightly coupled to Bootstrap for the future." is not really valid, since when we would change from bootstrap, we would have way bigger problems then just our form library (like our entire HTML markup).

**Comment by randx** [comment]
@jvanbaarsen I agree with you. First, I can not imagine GitLab without bootstrap. And seconds @Soullivaneuh already did quite big amount of job already. It would be waste if we loose this progress. I am absolutely ok with `rails-bootstrap-forms` as soon as it nicely implemented without breaking UI on any page

**Comment by Soullivaneuh** [comment]
Ok so I continue on this way. :+1:

**Comment by Soullivaneuh** [comment]
Weird rendering on application settings form:

gitlab_visibility_form

**Comment by dblessing** [comment]
Hi @Soullivaneuh Do you have time to come back to this?

**Comment by Soullivaneuh** [comment]
@dblessing I nearly finish admin section. But vendor bugs are still here.

Maybe it would be better to juste let bootstrap-form implementation, configuration and documentation and continue integration on another PRs.

**Comment by Soullivaneuh** [comment]
ping @dblessing

**Comment by jvanbaarsen** [comment]
This merge request has been closed because a request for more information has not been reacted to for more than 2 weeks. If you respond and conform to the merge request guidelines in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#pull-requests) we will reopen this merge request.

**Comment by Soullivaneuh** [comment]
@jvanbaarsen AFAIK, I'm still waiting an answer of @dblessing.

**Pull request closed without merging**
