### PR TITLE
Version 7.10.0 has been released so its 7.11.0-pre time

### PR DESCRIPTION
**Pull request by jvanbaarsen**
Version 7.10.0 has been released, so I think the *-pre should be dropped.

### CODE REVIEW

**Comment by maxlazio** [comment]
@jvanbaarsen Since 7.10 has been released we should be ad `7.11.0.pre` :)

**Comment by jvanbaarsen** [comment]
@maxlazio Ah ok :D Almost good :P Will fix tomorrow :)

**Comment by jvanbaarsen** [comment]
@maxlazio Fixed.

**Comment by Razer6** [comment]
Thank you

**Pull request merged**
