### PR TITLE
Allow mass-unassigning of issues

### PR DESCRIPTION
**Pull request by rspeicher**
Fixes https://gitlab.com/gitlab-org/gitlab-ce/issues/867

Also renames the spec file to correctly match its alternate file's name.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://tsigo-rs-issue-867.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://tsigo-rs-issue-867.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by randx** [comment]
@tsigo can you please add CHANGELOG item?

**Comment by randx** [comment]
@tsigo can you please add CHANGELOG item?

**Comment by tsigo** [comment]
@randx Done.

**Pull request merged**
