### PR TITLE
Allow developers to accept merges to protected branches

### PR DESCRIPTION
**Pull request by ievgrafov**
Patch adds two options for protected branches:
1) developers_can_merge - if enabled, developers will be allowed to accept merge requests not authored by any developer except themselves
2) authors_can_merge - if enabled, developers will be allowed to accept merge requests authored by themselves
If both options are enabled developers will be allowed to accept any merge requests

Functionality is needed to make developers review code written by teammates. Developers are unable to push code into protected branch but can create merge request and wait while one of their teammates review and accept it. Masters are not required to come after code-review and accept reviewed request because reviewer can do it himself.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://dilcom-feature-devs-can-merge-to-protected-branches.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://dilcom-feature-devs-can-merge-to-protected-branches.c68bfdc4cac4c32c41e1a922e73062ea.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by jvanbaarsen** [comment]
@dilcom I'm not really sure about this feature, it makes the authorisation process a lot  more complicated. @dosire / @randx What do you think?

**Comment by dosire** [comment]
How does this deal with merges via the command line interface? Are these also vetted?

**Comment by randx** [comment]
This goes too complex. I am not big fan of this feature

**Comment by dilcom** [comment]
I believe that feature can find it's fans among small teams not having master for each project they develop. Out team works on several small projects each developed by 2-3 devs. Now code goes to master branch without any restrictions and I want to make it go through several checks (build, static analyze, tests and finally code-review). Of course last restriction can be implemented via protecting branch and control by master but we can't make one of devs master because both of them commit to repository and their code need to be reviewed.

Merges via command line interface require push rights. Such merges will require master to accept it after developers review.

Forgot to add imgs of gui.
Before


After

**Comment by maxlazio** [comment]
This adds too much complexity for too little gain in my opinion.

**Comment by dilcom** [comment]
Hm, will it be easier if I remove option "authors can merge"? So each protected branch will have options "developers can push" (already implemented) and "developers can merge" in order to make developers to review code written by each other before merging it into protected branch. This change will have the same structure as already proposed but 1 additional column in table (, method in project controller etc) instead of 2.

**Comment by sebastienbonami** [comment]
@jvanbaarsen @dosire @randx @maxlazio In my company, we started to want to use Merge Requests in GitLab. We noticed Developers can't accept them even when "Developers can push" is enabled, but they can merge via the command line interface. That's inconsistent in my opinion. I completely share what @dilcom said and the patch he submits would meet my need! If I understand, it was deleted? I like the protected branches, because it's a security to prevent deleting or force pushing the master branch. On the other hand, I don't want to give the Master role for all my developers, because they could edit the projects, etc.

**Comment by randx** [comment]
> We noticed Developers can't accept them even when "Developers can push" is enabled, but they can merge via the command line interface. That's inconsistent in my opinion.

This looks like a bug and should be fixed.

**Comment by sebastienbonami** [comment]
Just to be clear, when I said that Developers can merge via the command line interface, I meant Git command line interface. Maybe you thought I was talking about GitLab command line interface (we don't use it).

**Comment by sebastienbonami** [comment]
Finally, I tried GitLab 7.10.1 and Developers can accept Merge Requests when "Developers can push" is enabled. So I guess it was a bug and it was solved in one of the latest versions.

**Comment by dosire** [comment]
@sebastienbonami Glad to hear that.

**Pull request closed without merging**
