### PR TITLE
Revert "Allow to configure smtp and sendmail in gitlab.yml"

### PR DESCRIPTION
**Pull request by dzaporozhets**
Reverts gitlabhq/gitlabhq#8800

### CODE REVIEW

**Comment by jvanbaarsen** [comment]
@randx Any reason you did not merge this yet?

**Comment by randx** [comment]
@jvanbaarsen I wanted to give author of original PR a time to fix compatibility problem so I dont need to revert it

**Comment by randx** [comment]
@jvanbaarsen but thank you for ping me

**Comment by randx** [comment]
cc @maxlazio @jacobvosmaer

**Pull request merged**
