### PR TITLE
Apply new header design for project graphs page

### PR DESCRIPTION
**Pull request by Totof6942**
Apply new header design for project graphs page like other pages.

Before : 

screenshot-gitlab com 2015-11-08 19-06-08

After :

screenshot-git e-keyleo fr 2015-11-08 19-05-44

Voilà.

### CODE REVIEW

**Comment by randx** [comment]
Yep thats good

**Comment by skyruler** [comment]
GUT

**Comment by randx** [comment]
Thanks

**Comment by Totof6942** [comment]
You're welcome, thanks for your work !

**Pull request merged**
