### PR TITLE
Add style for <kbd> element in markdown

### PR DESCRIPTION
**Pull request by afc163**
https://github.com/gitlabhq/gitlabhq/issues/5825

<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>F5</kbd>

### CODE REVIEW

**Comment by jvanbaarsen** [comment]
Restarted the build

**Comment by jvanbaarsen** [comment]
@afc163 Can you please add an entry to the CHANGELOG?

**Comment by afc163** [comment]
Done.

**Comment by jvanbaarsen** [comment]
@afc163 Thanks! Can you make this mergeable, and squash the commits? After that I'll merge

**Comment by afc163** [comment]
Fixed in #9295

**Pull request closed without merging**
